### ISSUE TITLE
Web UI 1.5

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2037] opened 2018-06-02 18:07 UTC
Unfortunately, I found some other small issues in the Web UI:

- [x] it is not possible to rename keys
- [x] "KDBError: Connection to instance failed." "stdout maxBuffer exceeded" (after mounting a very large keyset with 39964 keys. We might need [maxBuffer: Infinity](https://github.com/przemyslawpluta/node-youtube-dl/issues/126)?)
- [x] ~~copy value makes key blue, is it possible to color the value?~~
- [x] ~~creating arrays with different visibility does not work ("user" is used). Or is it even generally broken? (also with normal keys?)~~
- [x] creating keys that already exist does not lead to an error
- [x] creating metadata that already exists as "Additional Metadata" does not lead to an error
- [x] when clicking out of dialogs changes are discarded (metadata)
- [x] drag&drop while pressing ctrl does not copy even though the green (+) sign is shown.
- [x] pressing enter does not accept dialogs (edit value, metadata dialog)
- [x] ~~there should be detailed information in showing the full error (for bug reports and similar)~~
- [x] success tick is shown before "kdb set" is called (e.g. in hosts plugin when you input invalid IP addresses: you first get a tick as if it were successful but then you get an KDBerror. The value is shown wrongly then.)
- [x] pressing enter in search again: search is not updated
- [x] removing keys while search is active does not work

merchandising/changelog:

- [x] describe changes in changelog (news)
- [x] create highlight text
- [x] add video+demo URL

not so important (It would be great to have them but might be okay to not have it.):

- [x] allow to directly create issues from the WebUI on errors (simply link to http://issues.libelektra.org/new)
- [x] version of webUI running is not shown

and as discussed:

- [x] first character broken
- [x] ~~make 3 Dockerfiles (base, elektrad, and web), mount+import some stuff to make it more interesting~~ -> #1901 
- [x] make more clear which errors are older (gray out?) and/or blink if a new error happens
- [x] array improvements (array as metadata)
- [x] http://127.0.0.1:33333 -> http://localhost:33333 (even if we now do not abuse localhost)
- [x] other points from meeting

if you want we can merge the PR #2029 first.

**Comment by omnidan** [comment] 2018-06-18 14:52
> it is not possible to rename keys

I think this is not really a feature that will be used a lot, you can always just duplicate and delete the other key. I could add a new button, but I think there are already too many buttons next to the items and it would only get more confusing.

> copy value makes key blue, is it possible to color the value?

Not easily with the current version of the library. Also, I tested it by editing css in the browser and it doesn't look that nice as the contrast between key/value gets lost:

![screen shot 2018-06-18 at 16 46 22](https://user-images.githubusercontent.com/668674/41543484-2e212f62-7317-11e8-9c87-c4a097bc8681.png)

> how to input a newline in value or metadata?

I don't think this is possible without turning the input field into a textarea or implementing a custom input field. Is this really such an important feature?

**Comment by markus2330** [comment] 2018-06-18 17:03
> I think this is not really a feature that will be used a lot, you can always just duplicate and delete the other key. I could add a new button, but I think there are already too many buttons next to the items and it would only get more confusing.

I missed it already several times. I think it is possible without any button: What about clicking on the key name?

>  I don't think this is possible without turning the input field into a textarea or implementing a custom input field. Is this really such an important feature?

No, it is nice to have.

> I noticed that this only happens with mounted keys.

Yes, if the mountpoint does not support meta data, it will be discarded. But I do not think this was the problem I had.

**Comment by omnidan** [comment] 2018-06-18 17:04
I added not so important problems with non-trivial solutions to the ideas issue #1849, the rest should be done now (except the ones mentioned above). I will work on the docker images tomorrow (I removed the task from here as it is already tracked in #1901).

**Comment by markus2330** [comment] 2018-06-18 17:12
Please do no move bugs to "ideas":

 -[ ] if no sub key is visible somewhere, an arrow (that has no useful function) is shown nevertheless. This is confusing when searching, because then the arrow might disappear.
- [ ] problems on concurrent editing

"meta-data arrays are not supported" should not be too hard to implement? Isn't the check/enum basically doing this?

**Comment by markus2330** [comment] 2018-06-18 17:12
Please do no move bugs to "ideas":

 - [ ]  if no sub key is visible somewhere, an arrow (that has no useful function) is shown nevertheless. This is confusing when searching, because then the arrow might disappear.
- [ ] problems on concurrent editing

"meta-data arrays are not supported" should not be too hard to implement? Isn't the check/enum basically doing this?

**Comment by omnidan** [comment] 2018-06-18 17:39
> I missed it already several times. I think it is possible without any button: What about clicking on the key name?

Good idea! I implemented that.

> Yes, if the mountpoint does not support meta data, it will be discarded. But I do not think this was the problem I had.

I tried creating a normal and an array key with visibility advanced, both worked fine. How can I reproduce this problem?

**Comment by markus2330** [comment] 2018-06-18 18:36
> Good idea! I implemented that.

Thank you :heart: 

> I tried creating a normal and an array key with visibility advanced, both worked fine. How can I reproduce this problem?

I'll try with http://webui.libelektra.org/ when it is available again (#1901).

> I had a look at this but it's not trivial to solve. I think concurrent editing is a good idea, but currently Elektra Web is quite far from supporting this.

Can you describe the problems? Does launching multiple elektrad solve the problem? The main problem with this problem is that it can easily occur in the live demo.

What about having a configuration setting for instances to not remember the tree view? (As workaround for this issue to be used in the live demo.)

> I moved this because it was in "not so important" and it is not easy to fix (at the moment I do not know how to fix it without rewriting the tree view library).

Hopefully you find a solution.

**Comment by omnidan** [comment] 2018-06-19 08:39
> I'll try with http://webui.libelektra.org/ when it is available again (#1901).

It is available, you just have to specify the port right now (will be fixed with multiple docker containers): http://webui.libelektra.org:33334/

> Can you describe the problems? Does launching multiple elektrad solve the problem? The main problem with this problem is that it can easily occur in the live demo.

Well, the main problem is that I cannot reproduce it. When I open two browser instances on my laptop the problem does not happen yet (even with http://webui.libelektra.org:33334/). I tried opening, closing and writing text on both windows, I didn't get a single error. Maybe it only happens when the requests (such as opening subkeys or entering data) get sent at the exact same time?

> What about having a configuration setting for instances to not remember the tree view? (As workaround for this issue to be used in the live demo.)

I think that would reduce the possibility of the issue happening, because synchronizing the tree view does a `kdb set` quite often. But as I said, I don't think it will happen unless many people use the demo at the same time.

**Comment by markus2330** [comment] 2018-06-19 11:38
> It is available

In the correct version?

> visibility

- press "Creating new key at user"
- enter "myname" as name
- press "CREATE ARRAY"
- press "Creating new key at user/myArray"
- First bug: name is `<empty>` and not `#0`
- Create a second sub key
- Second bug: name should be `#1` and not `#5`

Are you sure the latest version is running?

>  Well, the main problem is that I cannot reproduce it.

Did you try to use auto-refresh? Or ask a second user, it was easily reproducible in the last meeting.

>  because synchronizing the tree view does a kdb set quite often

It should use `kdb set` exactly once. Did you fix this problem?

**Comment by omnidan** [comment] 2018-06-19 12:11
> In the correct version?

No, it is still the old version.

> Did you try to use auto-refresh? Or ask a second user, it was easily reproducible in the last meeting.

It does not happen with just two people working on it at the same time, we can try reproducing it again in the next meeting.

> It should use kdb set exactly once. Did you fix this problem?

It does use it exactly once. However, it is called every time you open or close a subtree.

**Comment by markus2330** [comment] 2018-06-19 13:41
I tried `docker run -d -it -p 33333:33333 -p 33334:33334 elektra/web` and arrays were broken there, too.

Can you please update all docker images now to contain Web-UI 1.5?

**Comment by omnidan** [comment] 2018-06-19 15:32
@markus2330 the docker image is already up-to-date. I just tried running the same command and arrays work fine for me there. Maybe you still have an old image in your cache?

**Comment by markus2330** [comment] 2018-06-19 16:01
No, it downloaded an image an hour ago. I'll create a new issue with instructions how to reproduce.

**Closed** 2018-06-19 17:46 UTC
