### ISSUE TITLE
KDB: Set Meta Command Without Value Fails Silently

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#2136] opened 2018-07-29 11:58 UTC
# Steps to Reproduce the Problem

```sh
kdb setmeta user/tests/array array
kdb getmeta user/tests/array array
# STDERR: Metakey not found
```

# Expected Result

Either the first command

1. should work (adding the meta key `array` containing an empty string), or
2. fail printing an error message to `stdout`

. I prefer the first option.

#  Actual Result

The first command fails silently.

# System Information

- Elektra Version: master
- OS: macOS 10.13.6

**Comment by markus2330** [comment] 2018-07-30 11:31
Thank you for reporting the problem!

It seems like that "setmeta" with 2 arguments removes the metakey. The idea was to avoid inconsistencies with "set", which adds a null-key and not an empty value.

**Comment by sanssecours** [comment] 2018-07-30 11:40
> It seems like that "setmeta" with 2 arguments removes the metakey. The idea was to avoid inconsistencies with "set", which adds a null-key and not an empty value.

Oh, that is interesting. Anyway, I still think the behavior is quite unintuitive, especially since we already have `kdb rmmeta` to remove metakeys.

**Comment by markus2330** [comment] 2018-07-30 12:00
Yes, it is unintuitive and I also forgot about that feature. So removing it sounds sensible but I moved it to 0.9 because it is a breaking change (scripts might rely on the current behavior).

**Comment by markus2330** [comment] 2019-02-17 21:23
This is a duplicate of #2388

**Closed by markus2330** 2019-02-17 21:23 UTC
Labels: duplicate, usability
