### ISSUE TITLE
plugin: internalnotification

### ISSUE THREAD

**Issue by waht** [ElektraInitiative/libelektra#825] opened 2016-07-09 17:22 UTC
@markus2330 asked me to create an [internalnotification plugin](https://github.com/waht/libelektra/tree/internalnotification/src/plugins/internalnotification) which updates variables automatically when registered keys are changed on kdbGet/kdbSet.

For now the plugin allows to register integer variables. It is assumed that the key value is a string containing a number.

The plugin is located in the [internalnotification](https://github.com/waht/libelektra/tree/internalnotification)-branch of my libelektra-fork.
I also created a [testbed program](https://github.com/waht/internalnotification-test).

Unit tests and memcheck are fine, but in the testbed only every second kdbGet triggers the plugin, the first kdbSet does not trigger (but afterwards it works fine).

Due to these issues I did not create a pull request yet.
Maybe the testbed program is flawed, but the placement of the plugin could also be wrong (postgetstorage for kdbGet, postcommit for kdbSet).

Maybe someone can help.

**Comment by markus2330** [comment] 2016-07-09 21:43
Do not worry about any issues, you can still create a PR, only mark it accordingly (WIP in title or "in progress" tag). Within an PR its easier to discuss the code and we can trigger the build server.

About kdbGet/kdbSet not happening: In the API usage of kdbGet()/kdbSet() you need to consider the state diagram doc/images/state.png. kdbSet() always needs a prior kdbGet(). kdbGet() might be a NOP if it detects that the configuration files are unchanged.

postgetstorage and postcommit sound ok.

Please integrate all tests within the same repo. And please run clang-format before creating the PR.

**Comment by waht** [comment] 2016-07-10 12:27
Allright, I created a PR :)
I did not include the testbed for now, since it is interactive and only useful for manual testing. Should I move it to the repository?

Regarding the state diagram, the testbed seems fine. There is an initial kdbGet() in main and the returned KeySet is passed to subsequent kdbSet/Get calls. I constructed a case where kdbSet() succeeds (the file is changed, plugin not triggered since it is the first kdbSet()) and the next kdbGet() does not trigger the plugin:

```
Press t to print "temperature"
Press g to kdbGet and print "greeting" key
Press s to set "temperature" key to a random value

elektraInternalnotificationOpen
elektraInternalnotificationRegisterInt variable=0x7ffd6b368d20, keyName=/sw/waht/elektra-test/temperature
elektraInternalnotificationRegisterInt registered key (name=/sw/waht/elektra-test/temperature, variable=0x7ffd6b368d20)
temperature variable located at 0x7ffd6b368d20
elektraInternalnotificationGet keyName=/sw/waht/elektra-test
elektraInternalnotificationUpdateRegisteredKeys looking up registeredKey=/sw/waht/elektra-test/temperature
elektraInternalnotificationUpdateRegisteredKeys found registeredKey=/sw/waht/elektra-test/temperature; updating variable=0x7ffd6b368d20 with string value 481062
kdbGet result was 1
t
"temperature" value = 481062
s
random value = 694854
kdbSet result was 1
t
"temperature" value = 481062
g
kdbGet result was 0
Key "/sw/waht/elektra-test/greeting" not found!
g
elektraInternalnotificationGet keyName=/sw/waht/elektra-test
elektraInternalnotificationUpdateRegisteredKeys looking up registeredKey=/sw/waht/elektra-test/temperature
elektraInternalnotificationUpdateRegisteredKeys found registeredKey=/sw/waht/elektra-test/temperature; updating variable=0x7ffd6b368d20 with string value 694854
kdbGet result was 0
Key "/sw/waht/elektra-test/greeting" not found!
t
"temperature" value = 694854
```

After the first kdbSet() the mtime of the file containing the key changes. As I understand, the next kdbGet() should not be a NOP here - the plugin is not triggered. The last kdbGet() (executed immediately after the former) does trigger the plugin.

**Comment by markus2330** [comment] 2016-07-11 16:56
Yes, please move testbed also to main repo. You could run some tests automated and alternatively provide an interactive mode selected command-line parameters.

Can you create a simplified test case and an extra issue for the problem with kdbGet() not doing anything. (maybe add it to testkdb_*) If your plugin does not trigger, also the others should not. You can add a tracer plugin for tests. Maybe the problem is related to global plugins?

**Comment by markus2330** [comment] 2016-10-12 20:22
Please close this issue with the PR.

**Closed** 2019-01-23 16:27 UTC
