### ISSUE TITLE
libelektra-proposal.so.4: cannot open shared object file: No such file or directory since upgrade to 0.9.1

### ISSUE THREAD

**Issue by tom-wa** [ElektraInitiative/libelektra#3305] opened 2019-11-29 20:17 UTC
after upgrading from 0.9.0 to 0.9.1 i get the error 
``` Sorry, 1 warning was issued ;(
        Sorry, module kdb issued the warning C01200:
        Installation: Dlopen failed. Could not load module
libelektra-hosts.so. Reason: libelektra-proposal.so.4: cannot open
shared object file: No such file or directory
        Mountpoint:
        Configfile:
        At:
/home/jenkins/workspace/libelektra_master/libelektra/src/libs/loader/dl.c:90
```

the file `libelektra-proposal.so.4` existed in 0.9.0 but not anymore in 0.9.1

**Comment by mpranj** [comment] 2019-11-29 21:16
Thank you for reporting!

To my knowledge some functions were removed from proposal, but not all. The library will be completely removed in future with #3201.

How did you obtain 0.9.1? Build from the tag or tarball or simply current master (i.e. above 0.9.1 actually) Did you compile yourself or obtain it from e.g. https://debian-stretch-repo.libelektra.org/pool/main/e/elektra/ ?

Is this on a clean installation? I don't see why the build system would not catch this, as it runs the tests of the host plugin.

Can you provide some more steps how to reproduce this situation.

**Comment by tom-wa** [comment] 2019-11-29 21:25
>How did you obtain 0.9.1? Build from the tag or tarball or simply current master (i.e. above 0.9.1 actually) Did you compile yourself or obtain it from e.g. https://debian-stretch-repo.libelektra.org/pool/main/e/elektra/ ?

installed it from the debian repositories.

>Is this on a clean installation?

issue happened on a clean installation first and i double-checked it by upgrading from 0.9.0 to 0.9.1 on an other installation. 


the system with the clean installation is clean newly set up debian 10.1 VM, the system with the upgraded is a former debian 9.5 unstable. 

downgrading back to 0.9.0 fixed the issue on both machines

**Comment by markus2330** [comment] 2019-11-29 21:25
It seems to be the problem of the Debian packages. I can reproduce this issue, e.g. with libelektra4 0.9.1-1.481 from the build server, hosts still links against libproposal.so but libelektra-proposal.so.4 is not available.

I think it is simply a bug in how we build the Debian package, We do not install libelektra-proposal but some plugins (like hosts) still need it.

@tom-wa for your the best option is to simply compile Elektra from scratch and install it (and not use the Debian packages).

But maybe 6df8d2f73f3b61a877fb3f3f9ec878a7f54ac6e4 fixes the problem.

**Comment by markus2330** [comment] 2019-11-29 21:25
> downgrading back to 0.9.0 fixed the issue on both machines

Then use 0.9.0 for your benchmarks.

**Comment by markus2330** [comment] 2019-12-02 07:00
I think we can close this now. With 0.9.1-1.631 I can call `kdb ls system/hosts` without any issues.

**Closed by markus2330** 2019-12-02 07:00 UTC
Labels: bug
