### ISSUE TITLE
Multiple tests failing with custom paths

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#1001] opened 2016-10-01 16:53 UTC
# Describe what you wanted to do

As described in [doc/TESTING.md](http://git.libelektra.org/blob/master/doc/TESTING.md) I tried to use custom paths for KDB_DB_SYSTEM and KDB_DB_SPEC using:

```
cmake -DDEBUG=ON -DVERBOSE=ON -DBUILD_STATIC=OFF -DCMAKE_INSTALL_PREFIX=./install -DKDB_DB_SYSTEM="~/.config/kdb/system" -DKDB_DB_SPEC="~/.config/kdb/spec" ..
```
# Describe what you expected

I expected it to parse the paths correctly.
# Describe what actually happened

The following tests FAILED:
     55 - testmod_resolver (Failed)
     77 - testscr_check_resolver (Failed)
It appears that the paths are not interpreted correctly as can be seen in the test logs attached.
Using **absolute paths works** as expected! (NB: without quotes)
# System Information
- Elektra Version: master
- OS: macOS
# Further Log Files and Output

[testmod_resolver.txt](https://github.com/ElektraInitiative/libelektra/files/504489/testmod_resolver.txt)
[testscr_check_resolver.txt](https://github.com/ElektraInitiative/libelektra/files/504490/testscr_check_resolver.txt)

**Comment by markus2330** [comment] 2016-11-22 17:03
I am afraid that the tests cannot pass by design (we would need to reimplement the resolver logic to catch all possibilities). Since d198beee045f9047c022e4da83c22b870b49bf5f the testcase outputs what the "problem" with the paths is:

```
55: /libelektra/src/plugins/resolver/testmod_resolver.c:57: error in test_resolve: string "/nonexistent/.config/kdb/system/elektra.ecf" is not equal "~/.config/kdb/system/elektra.ecf"
55: /libelektra/src/plugins/resolver/testmod_resolver.c:67: error in test_resolve: string "/nonexistent/.config/kdb/system/elektra.ecf" is not equal "~/.config/kdb/system/elektra.ecf"
55: Resolve Name
55: /libelektra/src/plugins/resolver/testmod_resolver.c:107: error in test_name: string "/nonexistent/.config/kdb/system/elektra.ecf" is not equal "~/.config/kdb/system/elektra.ecf"
```

(above as nobody) and as root:

```
55: /libelektra/src/plugins/resolver/testmod_resolver.c:57: error in test_resolve: string "/root/.config/kdb/system/elektra.ecf" is not equal "~/.config/kdb/system/elektra.ecf"
55: /libelektra/src/plugins/resolver/testmod_resolver.c:67: error in test_resolve: string "/root/.config/kdb/system/elektra.ecf" is not equal "~/.config/kdb/system/elektra.ecf"
55: Resolve Name
55: /libelektra/src/plugins/resolver/testmod_resolver.c:107: error in test_name: string "/root/.config/kdb/system/elektra.ecf" is not equal "~/.config/kdb/system/elektra.ecf"
```

So it seems like the resolver works with `~` as expected, but the test cases do not handle this situation.

**Comment by markus2330** [comment] 2016-11-22 17:34
Btw. a very much related issue is that the testcases in tests/shell/check_resolver.sh. The solution for there is to keep `$HOME` and use it for resolving (as the shell does with `~`). Maybe we can reuse this approach for `testmod_resolver`.

**Closed** 2019-02-07 14:31 UTC
Labels: enhancement, low priority
