### ISSUE TITLE
qt-gui: issues with searching

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#233] opened 2015-07-13 08:33 UTC
There are various issues with the searching feature.

1.) user/guitest/a/b is not found when searched for guitest

2.) searching for guitest/a/b yields nothing (is / allowed?)

3.) too many hits causes problems with the scroll bar (e.g. when searching for "b"). When scrolling around the hits suddenly disappear.

Some errors that occur during searching (maybe unrelated):
```
qrc:/qml/KeyWindow.qml:21: TypeError: Cannot read property 'path' of null
qrc:/qml/main.qml:812: TypeError: Cannot call method 'get' of undefined
```

Feel free to split the issues, I am not sure if and how they relate to each other.

**Comment by 0003088** [comment] 2015-07-14 14:41
1) That's strange, I have to investigate.
2) No, slashes are not supported atm, but could be implemented of course. Maybe if the user enters a key with slashes the result contains only the expected key if present and no further keys that include parts of the name? Like an exact search? Or should the string be split and the result contain all keys that have one of the parts in their name?
3) The problem seems to be that the model is still populated with keys while it is already shown to the user, looks like this confuses qt. The only quick solution I can think of atm is presenting the user some kind of progress bar while the search is performed and to add the model to the view only after it is fully populated?

**Comment by 0003088** [comment] 2015-07-21 09:47
1) and 2) should be fixed, the reason I suggested as explanation for 3) is not correct, the issue seems to be caused by some caching problem in the list view or something. Still need to find some solution.

**Comment by markus2330** [comment] 2015-07-22 14:30
Great! Thanks for your efforts!

Hope to see the other fix, too.

**Comment by markus2330** [comment] 2015-10-06 10:02
Any progress on the third issue? Should we open a new bug for it?

**Comment by 0003088** [comment] 2015-10-06 14:52
> Any progress on the third issue? Should we open a new bug for it?

I think a new bug might be a good idea. I'm pretty sure the issue is a problem in Qt, I will file a bug report with them.

**Closed** 2015-10-07 18:33 UTC
Labels: bug, question
