### ISSUE TITLE
kdb editor cannot deal with commas when using ni

### ISSUE THREAD

**Issue by Piankero** [ElektraInitiative/libelektra#2415] opened 2019-02-13 22:00 UTC
## Steps to Reproduce the Problem

Checkout https://github.com/ElektraInitiative/lcdproc/tree/elektra_tutorial
Mount the specification:
```sh
sudo kdb mount '<path_to_repo>/lcdproc-elektra/server/specification/LCDd-spec.ini' 'spec/sw/lcdproc/lcdd/#0/current' ni
sudo kdb spec-mount '/sw/lcdproc/lcdd/#0/current'
```

Call the editor with the `ni` plugin
```sh
kdb editor '/sw/lcdproc/lcdd/#0/current/curses' ni
```
Change any value (eg. background = green)

Save the configuration
## Expected Result

The configuration merges correctly.

## Actual Result

```
1 conflicts were detected that could not be resolved automatically:
/sw/lcdproc/lcdd/#0/current/curses/background
ours: , theirs: 

Merge unsuccessful.
```

#2332

**Comment by markus2330** [comment] 2019-02-14 18:41
Is this a duplicate of #1288?

We really should disable the cascading keys for `kdb editor` for now.

As workaround:
```
kdb editor 'spec/sw/lcdproc/lcdd/#0/current/curses' ni
```
should work.

**Comment by Piankero** [comment] 2019-02-15 18:50
But then you cannot edit values other than those of the spec namespace, right?

**Comment by markus2330** [comment] 2019-02-15 19:03
You, can edit any namespace but you need to edit them separately.

**Closed** 2019-02-17 21:40 UTC
Labels: duplicate
