### ISSUE TITLE
master fails

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4837] opened 2023-01-23 11:27 UTC
the last master builds failed (despite PR builds being successful.

https://build.libelektra.org/job/libelektra/job/master/975/display/redirect
https://build.libelektra.org/job/libelektra/job/master/974/display/redirect

```
	 27 - testcpp_kdb (Failed)
	 33 - test_context (Failed)
	 40 - testshell_markdown_base64 (Failed)
```

with also plenty of reported memleaks.

I retriggered:

https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/master/976/pipeline

**Comment by kodebach** [comment] 2023-01-23 13:40
I think this may be the temporary failures that started a while ago, but were hidden by `--rerun-failed` until #4778 was merged.

The error in `testcpp_kdb` is exactly the weird error that I saw in #4671 and have not encountered outside of Jenkins. I also still can't explain the error in any way other than "something on Jenkins deleted `elektra.ecf` while tests where running".

In `test_context` it seems the `intercept/env` binding didn't do the cleanup for some reason. Maybe there is a codepath, where cleanup isn't properly triggered, e.g. maybe `exit()` or `abort()` was used which wouldn't trigger C++ destructors.  However, I have basically zero knowledge about the `intercept` binding and `contextual` stuff, so it may be something entirely different.

As for `testshell_markdown_base64` I believe there is probably no issue there. It was simply the first `testshell_*` test. So if something before left an unclean KDB (e.g. `test_context`), it may not be detected until `testshell_markdown_base64`. The error probably goes away, when the other issues are fixed.

**Comment by markus2330** [comment] 2023-01-23 14:28
Yes, I was afraid that it is caused by https://github.com/ElektraInitiative/libelektra/pull/4778.
So we could enable rerun-failed again (correctly) or disable all flaky tests.

**Comment by kodebach** [comment] 2023-01-23 15:47
It is **caused by** #4778. The PR made the errors more noticeable, but the bugs have existed before.

Like I said I have basically no knowledge to help with fixing `test_context`. And for `testcpp_kdb` the only idea I had is, something being broken in Jenkins (there shouldn't be anything deleting stuff, while tests are running). Since I cannot solve that either, I unassigned myself.

**Comment by kodebach** [comment] 2023-02-03 14:03
I've only seen it in PRs, but I'll add it to this issue since it'll probably happen on `master` at some point. I believe there is also an issue with `test_getenv`. See e.g. https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/PR-4717/15/pipeline

It involves the same `bindings/intercept/env` stuff as `test_context` so I suspect it's the same bug.

**Comment by atmaxinger** [comment] 2023-02-06 18:15
Another test that is extremely flakey for my decision (!) PRs is `testmod_dbusrecv`.

**Comment by kodebach** [comment] 2023-02-06 20:35
Was this also on jenkins? The error message looks more like macOS.

If I remember correctly `testmod_dbusrecv` (especially on macOS) was one of the tests that originally lead to the introduction of `--rerun-failed` in the `run_all` script. If the test is causing problems again, we should probably run it with a separate `ctest` call with e.g. [`--repeat=until-pass:5`](https://cmake.org/cmake/help/latest/manual/ctest.1.html#cmdoption-ctest-repeat).

**Comment by atmaxinger** [comment] 2023-02-06 20:57
Yes, this was on macOS

**Comment by markus2330** [comment] 2023-02-08 13:55
There were very long discussions that I said it is **not** a good idea to simply disable `--rerun-failed`. Now we are in a bigger mess than before.

**Comment by kodebach** [comment] 2023-02-08 14:27
I originally added `ELEKTRA_AUTO_RERUN` exactly, because of the potential for failing tests on CIs other than Jenkins. We would've simply set `ELEKTRA_AUTO_RERUN=1` in the CI config where needed. You, markus2330, didn't like it and [wanted it to be removed](https://github.com/ElektraInitiative/libelektra/pull/4778#issuecomment-1382876669).

I'll create a PR to modify the various CI configs to rerun the `testmod_dbusrecv` test.

**Comment by kodebach** [comment] 2023-02-08 15:29
See #4842 for an attempt of using `--repeat until-pass:5` limited to problematic tests.

**Comment by markus2330** [comment] 2023-02-08 16:20
Thank you for working on it!

`ELEKTRA_AUTO_RERUN` doesn't solve anything (please do not try to reintroduce with different names e.g. AUTO_RERUN_TESTS). In CI we can either hard-code rerun ([ci_run_tests.sh](https://github.com/ElektraInitiative/libelektra/pull/4842/files#diff-ff865e9cc7977b4c2d52273c495998823c07beb0fec30e4ac3c4d5dd8f8a355d) already implies that this is only for CI) or we don't (for developers). The issue is solved if either:

1. builds do not weirdly fail even though the rerun succeeded
2. we disable (or completely remove) broken code/broken testcases (e.g. the whole contextual stuff probably should be removed as it is not used by anyone)

Imho 2. is the better solution than 1. but it is also more work (thus I wouldn't have started it). As we now exposed the broken tests, we might attempt to fix at least a few of them.

**Comment by markus2330** [comment] 2023-02-08 16:21
Btw. https://build.libelektra.org/job/libelektra/job/master/984/display/redirect again failed, it is quite rarely that a master job succeeds, see https://build.libelektra.org/job/libelektra/job/master/

**Comment by kodebach** [comment] 2023-02-08 16:30
1. `ELEKTRA_AUTO_RERUN` was meant to be enabled in Cirrus and Github Actions and ignored everywhere else. It would have restored the previously working situation, where: Jenkins doesn't use `run_all` and Cirrus/Actions use `run_all` with `--rerun-failed`. The change would've been that when you use `run_all` locally, you wouldn't get the useless `--rerun-failed`.
2. `AUTO_RERUN_TESTS` in #4842 is a more sophisticated solution. It lists all tests that should be executed with `--repeat until-pass:5`. That way these tests are rerun on failure up to 5 times. By using a separate variable, we can limit this behaviour to known flaky tests (like `testmod_dbus*`). This avoids (A) having to wait for multiple failed runs for other broken tests and (B) it doesn't hide newly flaky tests.
3. I agree all the contextual stuff should be removed.
4. I still cannot explain the error in `testcpp_kdb` with anything other than: There is a concurrent process that deletes files created by the test. Since this only happens on Jenkins, I suspect there is something wrong with our setup. Otherwise `testcpp_kdb` would also sometimes fail locally and on other CIs.

**Comment by atmaxinger** [comment] 2023-03-01 19:31
Why do we always have [random memory leaks](https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/master/992/pipeline) on Jenkins or suddenly disappearing files?

**Closed** 2023-05-15 12:14 UTC
