### ISSUE TITLE
Undelete external deleted keys on synch

### ISSUE THREAD

**Issue by raetiacorvus** [ElektraInitiative/libelektra#761] opened 2016-05-31 11:33 UTC
I am using `gelektra_keyset_lookup(…, KDB_O_POP)` to delete a key and `gelektra_kdb_set(…)` to save the change. Opening Elektra Qt Editor after the calls shows the changes correctly. If execute the delete commands  while Elektra Qt Editor is running, using the `synchronize` action will undelete the key i deleted outside of Elektra Qt Editor.

It does not behave that way if i only change the value. It works correctly in that case. Maybe related to #760 and #706 ?

**Comment by markus2330** [comment] 2016-05-31 12:49
Thank you for reporting, I can reproduce the behaviour using `kdb`:
```
kdb qt-gui
kdb rm user/guitest/a
# press synchronize
kdb rm user/guitest/a
```

The last removal is also successful, but should not be.

I do not think its related with  #760, e.g. see with `kdb shell`:
```
kdb set user/test
kdb shell
shell> kdbGet user/test
kdb rm user/test
shell> kdbGet user/test # does not matter (#760)
shell> kdbSet user/test
kdb rm user/test # not found
shell> kdbGet user/test # this is the problem, got key again
```

Btw. its always good if you try to reproduce it in a standalone unit test, the qt-gui does too many things to easily tell where the problem is (thanks to @fberlakovich the synchronization  is now unit tested, too: src/libs/tools/tests/testtool_mergingkdb.cpp).
I also reproduced it in these c++ unit tests, see dd14555dfc183b1aff6040b78f1f899cdea090eb

**Comment by markus2330** [comment] 2016-10-12 20:06
Issue seems to be fixed now. Could not reproduce initial described issue.

**Closed by markus2330** 2016-10-12 20:06 UTC
