### ISSUE TITLE
Web UI completely ignores the specification of configuration settings

### ISSUE THREAD

**Issue by Piankero** [ElektraInitiative/libelektra#2410] opened 2019-02-11 21:49 UTC
I have mounted a specification as follows:
```
sudo kdb mount ..../server/specification/LCDd-spec.ini 'spec/sw/lcdproc/lcdd/#0/current' ni
sudo kdb spec-mount '/sw/lcdproc/lcdd/#0/current
```
One setting has the following metadata:
```
[/curses/background]
type = enum
check/type = enum
check/enum = red, black, green, yellow, blue, magenta, cyan, white
default = cyan
description = background color when "backlight" is off
```
When I type in the following command in the commandline I correctly receive an error message:
```
kdb set '/sw/lcdproc/lcdd/#0/current/curses/background' greeeeen 
#> Using name user/sw/lcdproc/lcdd/#0/current/curses/background
#> The command kdb set failed while accessing the key database with the info:
#> Sorry, the error (#121) occurred ;(
#> Description: validation failed
#> Reason: Validation of key "user/sw/lcdproc/lcdd/#0/current/curses/background" with string "greeeeen" failed.
#> Ingroup: plugin
#> Module: enum
#> At: ....../src/plugins/enum/enum.c:218
#> Mountpoint: user/sw/lcdproc/lcdd/#0/current
#> Configfile: ...../LCDd.conf.25676:1549919217.284067.tmp
```
But when I type in the same wrong value in the WEB-GUI the key gets accepted without any error message and is even retrievable via `kdb get` then in the command line.

#2332

**Comment by markus2330** [comment] 2019-02-15 18:44
Actually it would be quite trivial to support meta-data. Instead of `kdb get/set <namespace>/<key>`, `kdb get/set -N <namespace> <key>` should do the trick.

@omnidan Do you maybe have time for some improvements in the web-ui?

**Comment by omnidan** [comment] 2019-02-17 12:46
@markus2330 unfortunately I do not have time for any of my open source projects at the moment, I have already found someone else to maintain my other projects such as [node-emoji](https://github.com/omnidan/node-emoji).

I think this could/should be implemented in the kdb nodejs "library" of the web gui: https://github.com/ElektraInitiative/libelektra/blob/master/src/tools/web/kdb.js

**Comment by markus2330** [comment] 2019-02-17 13:58
Thank you for the tip!

**Comment by goJoWe16** [comment] 2019-04-03 10:01
@markus2330 

In the current version of the web-ui of libelektra, this validation check of specifications seems to be working just fine

![Bildschirmfoto von 2019-04-03 11-58-38](https://user-images.githubusercontent.com/17863315/55470582-32971500-5608-11e9-8388-a1c3ca7e4b69.png)

**Comment by goJoWe16** [comment] 2019-04-03 10:14
In the current version of the web-ui, the validation check of specifications seems to be working just fine testing the case provided in this issue

![Bildschirmfoto von 2019-04-03 12-13-14](https://user-images.githubusercontent.com/17863315/55471448-11cfbf00-560a-11e9-91ce-8f61cb827f5d.png)

**Comment by markus2330** [comment] 2019-04-03 12:20
@Piankero can you retry and give more detailed infos of how to reproduce this problem?

**Comment by raphi011** [comment] 2020-04-13 17:11
The current web-ui renders radio buttons for an enum key so this should be fixed.

**Closed** 2020-04-13 19:30 UTC
