### ISSUE TITLE
www.libelektra.org down

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4795] opened 2022-12-30 15:00 UTC
Website is down `Uncaught Error: [$injector:modulerr] Failed to instantiate module elektra.rest.angular due to:
Error: State 'main.dyn.installation' is already defined`

Maybe due to #4794? I created #4794 to revert it.

Help appreciated.

**Comment by markus2330** [comment] 2023-01-01 09:52
@lukashartl Can you please also think about how we can check this kind of outage with monit?

**Comment by lukashartl** [comment] 2023-01-01 13:50
> @lukashartl Can you please also think about how we can check this kind of outage with monit?

Adding a monit check that checks for a valid HTTP Response (>=200,<400) is easy.
But to also check whether we get valid JavaScript, would require to spawn a browser (Selenium, ...) and actually open the webpage every x minutes.

**Comment by markus2330** [comment] 2023-01-01 14:15
Yeah, it makes more sense that we let the build process fail in such cases. Unfortunately we don't know yet what is the cause and why the build succeeded.

I now tried to build it locally, and got following error during `make install`:
```
npm WARN deprecated angular-animate@1.8.3: For the actively supported Angular, see https://www.npmjs.com/package/@angular/core. AngularJS support has officially ended. For extended AngularJS support options, see https://goo.gle/angularjs-path-forward.
npm WARN deprecated angular-sanitize@1.8.3: For the actively supported Angular, see https://www.npmjs.com/package/@angular/core. AngularJS support has officially ended. For extended AngularJS support options, see https://goo.gle/angularjs-path-forward.
npm WARN deprecated angular@1.8.3: For the actively supported Angular, see https://www.npmjs.com/package/@angular/core. AngularJS support has officially ended. For extended AngularJS support options, see https://goo.gle/angularjs-path-forward.
npm WARN deprecated opn@6.0.0: The package has been renamed to `open`
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! website@1.0.2 postinstall: `./node_modules/grunt-cli/bin/grunt install`
npm ERR! Exit status 6
npm ERR! 
npm ERR! Failed at the website@1.0.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

and in the log:

```
1186 error code ELIFECYCLE
1187 error errno 6
1188 error website@1.0.2 postinstall: `./node_modules/grunt-cli/bin/grunt install`
1188 error Exit status 6
1189 error Failed at the website@1.0.2 postinstall script.
1189 error This is probably not a problem with npm. There is likely additional logging output above.
```

Looks rather unrelated to https://github.com/ElektraInitiative/libelektra/pull/4794?

@Namoshek Can you maybe help out here?

**Comment by Namoshek** [comment] 2023-01-01 21:01
I cannot reproduce this locally on Debian 10 (WSL). I see the `npm WARN` and some `npm notice`, but not the error.

**Comment by markus2330** [comment] 2023-01-02 06:33
@Namoshek Thank you for looking into it! And did this website you were able to produce work?

Ok, my `npm ERR` might be some local problem. It wasn't there a few weeks ago, though.
What my test showed nevertheless is that `make install` doesn't fail despite of npm errors.

https://build.libelektra.org/job/libelektra/job/master/946/consoleText also doesn't have a `npm ERR!`. It doesn have plenty of additional `npm WARN`, though, e.g.:

```
npm WARN deprecated chokidar@1.7.0: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN config production Use `--omit=dev` instead.
```

Unfortunately, it is not clear which of the warnings belong to the website build...

Maybe we need to build it more similar to the buildserver. Here a first start. Assuming we are inside a folder where libelektra master is checked out:

`DOCKER_BUILDKIT=1 docker build -t buildelektra-website --build-arg JENKINS_USERID=$(id -u) --build-arg JENKINS_GROUPID=$(id -g) -f scripts/docker/website/Dockerfile .`

```
 => => # npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142                                                                                                                                                  
 => => # npm WARN deprecated angular-sanitize@1.8.3: For the actively supported Angular, see https://www.npmjs.com/package/@angular/core. AngularJS support has officially ended. For extended AngularJS support options, see https://goo.gle/angularjs-path-forward.         
 => => # npm WARN deprecated angular-animate@1.8.3: For the actively supported Angular, see https://www.npmjs.com/package/@angular/core. AngularJS support has officially ended. For extended AngularJS support options, see https://goo.gle/angularjs-path-forward.          
 => => # npm WARN deprecated angular@1.8.3: For the actively supported Angular, see https://www.npmjs.com/package/@angular/core. AngularJS support has officially ended. For extended AngularJS support options, see https://goo.gle/angularjs-path-forward.                  
 => => # npm WARN deprecated docsearch.js@2.6.3: This package has been deprecated and is no longer maintained. Please use @docsearch/js.                                                                                                                                      
 => => # npm WARN deprecated mkdirp@0.3.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
```

**Comment by mpranj** [comment] 2023-01-02 11:40
I think most of the mentioned (deprecation) warnings have been there for quite some time.

The problem was that multiple menu-entries with the same reference were created. (`Error: State 'main.dyn.installation' is already defined`). You're right, it seems it was introduced by #4756, but I fixed only the offending occurences instead of a complete revert.

I updates the website manually and will push the fix shortly.

**Closed** 2023-01-02 11:52 UTC
Labels: urgent

**Comment by markus2330** [comment] 2023-01-03 11:31
Thank you so much for fixing it! I created  #4803 as follow-up to avoid this problem in the future.

Can you share (in #4803) some insight of how you debugged the problem? How did you find out which part of the file is broken?
