### ISSUE TITLE
gir fails linking

### ISSUE THREAD

**Issue by beku** [ElektraInitiative/libelektra#225] opened 2015-05-23 08:03 UTC
Here is the next OBS issue:

[  113s] cd /home/abuild/rpmbuild/BUILD/elektra-150523.094111git48964fe7/build/src/libtools/src && /usr/bin/c++   -Delektratools_EXPORTS -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g  -std=c++98  -Wno-deprecated-declarations  -Wstrict-null-sentinel -Wno-missing-field-initializers -Wold-style-cast -Woverloaded-virtual  -Wsign-promo  -Wno-long-long -pedantic -Wno-variadic-macros -Wall -Wextra -Wno-overlength-strings -Wsign-compare -Wfloat-equal -Wformat-security -Wshadow -Wcomments -Wtrigraphs -Wundef -Wuninitialized -Winit-self -Wmaybe-uninitialized -O3 -DNDEBUG -fPIC -I/home/abuild/rpmbuild/BUILD/elektra-150523.094111git48964fe7/build/src/include -I/home/abuild/rpmbuild/BUILD/elektra-150523.094111git48964fe7/src/include -I/home/abuild/rpmbuild/BUILD/elektra-150523.094111git48964fe7/build/src/bindings/cpp/include -I/home/abuild/rpmbuild/BUILD/elektra-150523.094111git48964fe7/src/bindings/cpp/include -I/home/abuild/rpmbuild/BUILD/elektra-150523.094111git48964fe7/build/src/libtools/include -I/home/abuild/rpmbuild/BUILD/elektra-150523.094111git48964fe7/src/libtools/include    -o CMakeFiles/elektratools.dir/plugin.cpp.o -c /home/abuild/rpmbuild/BUILD/elektra-150523.094111git48964fe7/src/libtools/src/plugin.cpp
[  113s] g-ir-scanner: link: cc -o /home/abuild/rpmbuild/BUILD/elektra-150523.094111git48964fe7/build/src/bindings/gi/tmp-introspect2hHyrs/GElektra-4.0 -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g /home/abuild/rpmbuild/BUILD/elektra-150523.094111git48964fe7/build/src/bindings/gi/tmp-introspect2hHyrs/GElektra-4.0.o -L. -Wl,-rpath=. -Wl,--no-as-needed -lgelektra-4.0 -L/home/abuild/rpmbuild/BUILD/elektra-150523.094111git48964fe7/build/lib -Wl,-rpath=/home/abuild/rpmbuild/BUILD/elektra-150523.094111git48964fe7/build/lib -lgio-2.0 -lgobject-2.0 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lglib-2.0
[  113s] /home/abuild/rpmbuild/BUILD/elektra-150523.094111git48964fe7/build/src/bindings/gi/tmp-introspect2hHyrs/GElektra-4.0: error while loading shared libraries: libelektra.so.4: cannot open shared object file: No such file or directory
[  113s] Command '['/home/abuild/rpmbuild/BUILD/elektra-150523.094111git48964fe7/build/src/bindings/gi/tmp-introspect2hHyrs/GElektra-4.0', '--introspect-dump=/home/abuild/rpmbuild/BUILD/elektra-150523.094111git48964fe7/build/src/bindings/gi/tmp-introspect2hHyrs/functions.txt,/home/abuild/rpmbuild/BUILD/elektra-150523.094111git48964fe7/build/src/bindings/gi/tmp-introspect2hHyrs/dump.xml']' returned non-zero exit status 127
[  113s] src/bindings/gi/CMakeFiles/gir.dir/build.make:64: recipe for target 'src/bindings/gi/GElektra-4.0.gir' failed
[  113s] make[2]: *** [src/bindings/gi/GElektra-4.0.gir] Error 1
[  113s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/elektra-150523.094111git48964fe7/build'
[  113s] CMakeFiles/Makefile2:7668: recipe for target 'src/bindings/gi/CMakeFiles/gir.dir/all' failed
[  113s] make[1]: *** [src/bindings/gi/CMakeFiles/gir.dir/all] Error 2
[  113s] make[1]: *** Waiting for unfinished jobs....

Looks like a -L flag order gelektra before the libelektra4.so -L path. Just a guess.

**Comment by markus2330** [comment] 2015-05-23 15:08
I think thats a problem of 48964fe7 fixed shortly afterwards.

Nothing happened in src/bindings/gi/ but in src/bindings/glib (which could be related) I changed the order of libraries to link in db20051ce9ac9a892f9d0e95248a7b8b38e26e0a. I changed it now back in 4fc2a1b67745d89c0540e92bcb3890a3ff381c3d, just in case. But more likely is that its caused by the CMake top-level inclusion issue fixed in 8570a6f5729f10f3885e98991d98bc8408f7205e.

With the more recent versions I cannot reproduce the problem and the build server compiled gi fine (8570a6f5729f10f3885e98991d98bc8408f7205e build log see here http://build.libelektra.org:8080/job/elektra-test-bindings/196/consoleFull)

**Comment by markus2330** [comment] 2015-05-23 15:14
Thank you for reporting and sorry for inconveniences.

I would like to collapse some other options to a single one, please tell me when you are finished so that potential other new introduced problems in master will not interfere with OBS builds. (I know round trip times on build servers can be troublesome and using fixed versions is not always easy to implement).

**Comment by beku** [comment] 2015-05-24 04:54
On a local build I can check the library link failure:
& ldd /var/tmp/build-root/openSUSE_Factory-x86_64/home/abuild/rpmbuild/BUILD/elektra-150523.233840git3738baba/build/lib/libgelektra-4.0.so
        linux-vdso.so.1 (0x00007ffcd9b97000)
        libelektra.so.4 => not found
        libgobject-2.0.so.0 => /usr/lib64/libgobject-2.0.so.0 (0x00007f16ce924000)
        libglib-2.0.so.0 => /usr/lib64/libglib-2.0.so.0 (0x00007f16ce616000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f16ce412000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f16ce06a000)
        libffi.so.4 => /usr/lib64/libffi.so.4 (0x00007f16cde62000)
        libpcre.so.1 => /usr/lib64/libpcre.so.1 (0x00007f16cdbf6000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f16cd9d8000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f16cedb7000)

Together with the linker line from the build output, it makes complete sense on the gcc level. Astonishing is, that I can't reproduce on my normal devel environment, even if all built libelektra.so* libraries are removed before.

What is ldd in Jenkins?

**Comment by beku** [comment] 2015-05-24 05:17
Given the already caused delay and that there is a more general provider of bindings - swig, I'd like to omit gir ATM in OBS and later in openSUSE rpm's.
One point which bothers me especially is that gir has its own linking helper tool, which appears not to work in the OBS context.
Feel free to close this issue as you please.

**Comment by markus2330** [comment] 2015-05-24 11:35
Hello,

Am Sonntag, 24. Mai 2015 schrieb Kai-Uwe Behrmann:
> On a local build I can check the library link failure:

With a link failure present no output file should be produced?

> & ldd
> /var/tmp/build-root/openSUSE_Factory-x86_64/home/abuild/rpmbuild/BUILD/ele
> ktra-150523.233840git3738baba/build/lib/libgelektra-4.0.so linux-vdso.so.1
> (0x00007ffcd9b97000)
>         libelektra.so.4 => not found

CMake should put a RPATH into all the libraries 
(/var/tmp/b....0git3738baba/build/lib/ in your case) and remove it when "make 
install" is used.

This is exactly what happens here:
http://build.libelektra.org:8080/job/elektra-test-bindings/ws/build/lib/

```
$ readelf -a libgelektra-4.0.so | grep RPATH
 0x000000000000000f (RPATH)              Library rpath: 
[/home/jenkins/workspace/workspace/elektra-test-bindings/build/lib:]
```
 
> Together with the linker line from the build output, it makes complete
> sense on the gcc level. Astonishing is, that I can't reproduce on my
> normal devel environment, even if all built libelektra.so* libraries are
> removed before.

Imho thats a different issue (unrelated to ldd problem above).

http://build.libelektra.org:8080/job/elektra-test-bindings/197/consoleFull

shows following:

```
Linking C shared library ../../../lib/libgelektra-4.0.so
cd /home/jenkins/workspace/workspace/elektra-test-
bindings/build/src/bindings/glib && /usr/bin/cmake -E cmake_link_script 
CMakeFiles/gelektra-4.0.dir/link.txt --verbose=1
/usr/bin/cc  -fPIC  -std=gnu99  -Wno-deprecated-declarations  -Wno-long-long -
pedantic -Wno-variadic-macros -Wall -Wextra -Wno-overlength-strings -Wsign-
compare -Wfloat-equal -Wformat-security -Wshadow -Wcomments -Wtrigraphs -Wundef 
-Wuninitialized -Winit-self -Wmaybe-uninitialized -fprofile-arcs -ftest-
coverage -Wsign-compare -Wfloat-equal -Wformat-security -O2 -g -DNDEBUG   -
fprofile-arcs -ftest-coverage -lgcov -shared -Wl,-soname,libgelektra-4.0.so -o 
../../../lib/libgelektra-4.0.so CMakeFiles/gelektra-4.0.dir/gelektra-
keyset.c.o CMakeFiles/gelektra-4.0.dir/gelektra-key.c.o 
CMakeFiles/gelektra-4.0.dir/gelektra-kdb.c.o ../../../lib/libelektra.so.0.8.11 
-lgobject-2.0 -lglib-2.0 -ldl -Wl,-
rpath,/home/jenkins/workspace/workspace/elektra-test-bindings/build/lib: 
```

Maybe its some kind of library ordering problem. Can you execute cc commands 
in the build directory? Try to shuffle around the -l* flags. Also make sure to 
build the latest version, as said there was a problem in CMake some commits 
ago.

best regards,
Markus

**Comment by beku** [comment] 2015-05-26 13:33
At this point I'd prefer to continue with other stack components.

Thanks for your help

**Comment by markus2330** [comment] 2015-07-11 12:03
Thank you for your OBS efforts. Please reopen the issue if needed.

**Closed by markus2330** 2015-07-11 12:03 UTC
Labels: enhancement
