### ISSUE TITLE
link checker fails

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3374] opened 2020-03-19 14:04 UTC
In #3366 and #3354 the link checker fails. This issue can be used for discussion what the problem is and how to solve it.

One way to solve the issue would be to support regex in the link-checker whitelist or do a "contains" instead of "equal" check for the whitelist. Then we simply could ignore github.com until the links work again.

In general we do not really have a way how we get rid of links that were whitelisted for temporary reasons. We could change the link checker that it also checks whitelisted links and simply does not fail for them but print that they actually do not fail anymore. Before releases, or more often, these links could be removed from the whitelist again.

What do you think?

**Comment by sanssecours** [comment] 2020-03-19 14:11
> What do you think?

I think this is a duplicate of issue #3373 😊.

**Comment by mpranj** [comment] 2020-03-20 14:12
Closed via #3376.

**Closed by mpranj** 2020-03-20 14:12 UTC
Labels: duplicate
