### ISSUE TITLE
mounting specification does not seem to work

### ISSUE THREAD

**Issue by Namoshek** [ElektraInitiative/libelektra#1144] opened 2016-11-29 15:21 UTC
I tried mounting the [configuration specification](../tree/master/src/tools/rest-backend/config-specification.ini) of my rest-backend. I placed the file in the install directory for specification files (KDB_DB_SPEC) and ran `kdb mount rest-backend-spec.ini spec/sw/elektra/restbackend/#0 ni`.

The mountpoint is created properly, but I do not get the defaults as I expected when using `kdb get /sw/elektra/restbackend/#0/current/backend/kdb/path/configs` for example. Did I make a mistake or is there an issue with the globbing?

I also tried adding a mountpoint in the specification like
```
[]
mountpoint = rest-backend-spec.ini
infos/plugins = simpleini
```
and adding it with `kdb spec-mount /sw/elektra/restbackend/#0` afterwards, but it doesn't seem to work either.

**Comment by markus2330** [comment] 2016-11-29 15:38
Thanks for reporting this issue!

> `kdb mount rest-backend-spec.ini /sw/elektra/restbackend/#0 ni`

You forgot `spec` here. Cascading mountpoints do not include `spec`.

> `kdb get /sw/elektra/restbackend/#0/current/backend/kdb/path/configs`

What exactly do you get? The spec keys and default keys?

> I also tried adding a mountpoint in the specification like

Where did you add this? Did you try `kdb setmeta spec/sw/elektra/restbackend/#0 mountpoint rest-backend.ini`.

What does `spec-mount` do then? Is the mountpoint listed in `kdb mount`?

(btw. rest-backend- **spec** .ini for non-spec is confusing).

**Comment by Namoshek** [comment] 2016-11-29 16:07
> You forgot spec here. Cascading mountpoints do not include spec.

Sorry, my fault. I used `spec` in the command, I just forgot it when writing down the command from mind. I added it to the top.

> What exactly do you get? The spec keys and default keys?

For `kdb ls /sw/elektra/restbackend` I get a list like
```
spec/sw/elektra/restbackend/#0/_/backend/api/description/html
spec/sw/elektra/restbackend/#0/_/backend/api/description/raw
spec/sw/elektra/restbackend/#0/_/backend/kdb/path/configs
...
```

For `kdb get /sw/elektra/restbackend/#0/current/backend/kdb/path/configs` (which has a default in the spec) I get `Did not find key`. Replacing the `_` with `current` returns the correct value (`dir/configs`).

> Where did you add this?

I added it to the config-specification.ini linked above and ran `kdb spec-mount /sw/elektra/restbackend/#0` after the other mount command.

> What does spec-mount do then? Is the mountpoint listed in kdb mount?

Yes it is listed like `rest-backend-spec.ini on /sw/elektra/restbackend/#0 with name <same again>`.

> (btw. rest-backend- spec .ini for non-spec is confusing).

Yes, it is. Sorry.

**Comment by markus2330** [comment] 2016-11-29 16:16
The purpose of spec-mount is to mount a cascading mountpoint with all plugins necessary (e.g. to do validation). It is not responsible for the `_`-resolving.

For the `_`-resolving you need the spec-plugin (Did you issue a `kdb global-mount`?) I added a note in c7dc7175f38989d4294f7fe1c4b35cfe7850b88aq

> Yes, it is. Sorry.

Maybe you can change it ;) (`mountpoint` in the spec file)

**Comment by Namoshek** [comment] 2016-11-29 16:22
Yes, spec is mounted globally.

**Comment by markus2330** [comment] 2016-11-29 16:24
@tom-wa Do you have an idea?

I will go through the setup now, lets see if I have the same issue.

**Comment by tom-wa** [comment] 2016-11-29 17:40
yeah, spec only copys the metadata to matching keys, but it doesn't create them (except for `assign/*` keys). i don't think it would be possible to create default keys with whitespaces

**Comment by Namoshek** [comment] 2016-11-29 18:05
Ok, in this case I'll have to rename the config keys from `_/...` to `current/...`, that seems to work.

Btw. creating the keys for wildcards could work if you take the parentKey and match it with the spec keys:
```
Spec:    spec/sw/elektra/restbackend/#0/_/some/key
Lookup:      /sw/elektra/restbackend/#0/current
```

**Comment by markus2330** [comment] 2016-11-29 18:15
> spec only copys the metadata to matching keys, but it doesn't create them

Why do they not match? When _ is replaced by current, it works?

But I am afraid the problem is something else: For `default` the spec plugin currently does nothing, #533 (and ksLookup is unable to match with `_`).

`assign` would be always preferred, so it cannot really be used as workaround.

>  i don't think it would be possible to create default keys with whitespaces

What do you mean with "whitespaces"? Do you mean with the spec key? Can you document this?

> Ok, in this case I'll have to rename the config keys from _/... to current/..., that seems to work.

Yes, for `default` keys this seems to be necessary.

> creating the keys for wildcards could work if you take the parentKey and match it with the spec keys:

What do you mean here?

Btw. there is a http://build.libelektra.org:8080/job/elektra-homepage/ build job (and a build agent with libjwt and cppcms installed, I have built debian jessie packages for these packages)

**Comment by markus2330** [comment] 2016-11-29 18:34
So let us use `current` instead of `_`, profiles for the rest-backend is not something that we need soon. (And with profile plugin it might even work nevertheless)

**Comment by tom-wa** [comment] 2016-11-29 18:45
>Why do they not match? When _ is replaced by current, it works?

because there doesn't seem to exist any key matching it in the other namespaces. when the _ gets replaced by current the normal behaviour for default keys applies

> What do you mean with "whitespaces"? Do you mean with the spec key? Can you document this?

sorry, meant wildcards

**Closed** 2016-12-09 22:56 UTC
