### ISSUE TITLE
Disabling tests on platform without mkdtemp (old Solaris) does not work

### ISSUE THREAD

**Issue by kraileth** [ElektraInitiative/libelektra#3449] opened 2020-06-01 07:16 UTC
## Background

After reading the latest (and last) article about Elektra on Pro-Linux I volunteered to give writing a port a try. I'm a member of the _Ravenports_ project, a universal packaging framework for *nix systems. The idea is to have buildsheets that can be used to produces packages for a variety of operating systems, such as DragonFly BSD, FreeBSD, Linux (glibc for now) and Solaris. For compatibility reasons we build on an ancient version of the latter, Solaris 10u8, so any programs run on versions >= 10u8 as well as illumos. Since this is usually the hardest platform I went off to work on that next after having the WIP port successfully built on FreeBSD (DF and Linux to be done later).

## Steps to Reproduce the Problem

I'm creating a build directory and then issue the following command:

`# cmake -DENABLE_TESTING=OFF ..`

## Expected Result

The additional define turns off testing. Required as only later versions of Solaris support _mkdtemp_.

## Actual Result

I'm getting the same result as without the define, suggesting to disable testing.

## System Information

- Elektra Version: 0.9.2 release
- Operating System: Solaris 10u8
- Versions of other relevant software: CMake 3.17.3

## Further Log Files and Output

> -- Looking for mkdtemp
>-- Looking for mkdtemp - not found
> CMake Error at tests/cframework/CMakeLists.txt:11 (message):
>  cframework requires mkdtemp && setenv, disable ENABLE_TESTING to build
>  without testing

**Comment by markus2330** [comment] 2020-06-01 14:59
> After reading the latest (and last) article about Elektra on Pro-Linux I volunteered to give writing a port a try.

These are great news! :fireworks: 

> I'm a member of the Ravenports project, a universal packaging framework for *nix systems. The idea is to have buildsheets that can be used to produces packages for a variety of operating systems, such as DragonFly BSD, FreeBSD, Linux (glibc for now) and Solaris.

Amazing :1st_place_medal:

> CMake Error at tests/cframework/CMakeLists.txt:11 (message):

Did you completely remove the build directory between the tries? I do not see how the tests/cframework gets included if tests are disabled. Does it say how tests/cframework/CMakeLists.txt got included?

Maybe it is related to #3446, and `-DBINDINGS="MAINTAINED;-io_uv;-io_ev;-io_glib"` is needed (exclusion of io bindings which currently do not work with `ENABLE_TESTING=OFF`).

**Comment by markus2330** [comment] 2020-06-04 12:52
Any update here? Does someone have an idea which plugin/binding causes the problem?

Is there some way to reproduce this with Linux?

**Comment by kraileth** [comment] 2020-06-04 19:39
Haven't had a lot of time this week, plan to take another stab at this over the weekend (giving your suggestion of defining the mentioned bindings together with disabling testing a try). Loosely related good news: I can confirm that Elektra builds fine on DragonFly BSD as is (with less plugins enabled compared to FreeBSD, though).

To answer your question: The build tool enforces clean builds. For each package a pristine build chroot is created and populated with all the build-time dependencies. So we can rule out previous attempts somehow polluting the environment.

What is your preferred Linux distro? I need to test the port on Linux, too, and might as well choose something best known by Elektra developers (as long is it isn't, say CentOS 6 or the like which ships a version of glibc too old for our bootstrap package and thus would require a (time-consuming) full platform bring-up :wink:).

**Comment by kraileth** [comment] 2020-06-06 15:13
Update: Just tried to use the line `cmake -DENABLE_TESTING=OFF -DBINDINGS="MAINTAINED;-io_uv;-io_ev;-io_glib" ..` and it didn't make any difference. CMake still hits this and gives the advice to disable ENABLE_TESTING.

Noticed #3452 - so I guess that I'm putting Solaris on halt for now and exclude that platform until the problem is resolved.

**Comment by markus2330** [comment] 2020-06-07 10:37
> What is your preferred Linux distro?

We use Fedora, Debian, Arch, Alpine among others. So you have plenty of choice. :wink: 

> I'm putting Solaris on halt for now

Yes, sounds reasonable. The goal was BSD anyway.

**Comment by mpranj** [comment] 2020-06-08 07:34
Thank you so much for working on this and reporting the problem.

I'm happy to take a look at this, but I don't have any Solaris OS where I could test this. Is there any quick way to spin up a Solaris 10u8 VM?

**Comment by kraileth** [comment] 2020-06-08 15:35
@markus2330 That'll be Arch for me in that case since I used that distro for many years before leaving for FreeBSD. I'd choose Alpine as I've always loved it, but Raven doesn't support Musl-based distros, yet. I'll get back in touch when I found the time to make the port ready for Linux (and will open a new issue if I run into trouble).

@mpranj My pleasure! Unfortunately Solaris being a proprietary platform, older releases are not so easy to come by. I had been on the hunt for this specific version for a while when I finally got my hands on it. Even installing the system is not that easy if you're not used to Solaris (which I wasn't at all). The easiest thing would probably be you giving me a public SSH key so I can grant you SSH access. We'd also have to agree on some date for me to make the server available as I don't have a static IP at home and would rather not take that machine to our data center (which would be quite a hassle to do + I have no idea if this meant infringement of the "for personal use" license). Drop me a line if you want to give it a try. My domain is elderlinux.org and the mailbox name is the same handle that I use here.

Regarding CI... I think that's complicated. Definitely don't bother with that very specific old Solaris version which is required for various reasons in Ravenports. Testing Elektra on either current closed-source Solaris - or better: on illumos - might make more sense. I took a quick look at Jenkins for another project quite some time ago. I could probably investigate providing e.g. an OmniOS VM as an external CI server. However this would be a long-term goal if I decide to become more involved with Elektra than just maintaining packages. Of course it would also require Java, which we don't support so far... Or maybe something like Buildbot would be an option? I'm not very knowledgable in the field of CI but nevertheless interested in that topic. Some time I want some basic CI for Raven package development to find out early when changes break any platform. Maybe I'll be able to share resources with Elektra for niche operating systems. But no promises on if or when that happens. :wink:

As long as there is no CI, I can offer the following: A lot of packagers don't seem very keen on providing the latest version. At RP we are. I saw that Elektra is listed on Wikidata as well and from my experience they are rather quick to pick up new versions. Therefore if my port is finished and becomes committed to Ravenports, we'll usually update to the latest version just a couple of days later. If something breaks I'll create an issue and if it get's fixed, I can attach patches to the port so that there's no need to just accept breakage until a new version is released.

**Comment by markus2330** [comment] 2020-06-08 19:41
> Arch

AUR usually has quite up-to-date packages: https://aur.archlinux.org/packages/elektra/ and https://aur.archlinux.org/packages/elektra-git/ but seems like they did not package 0.9.2 yet.

> I can offer the following

This sounds wonderful :rocket:

**Comment by mpranj** [comment] 2021-04-14 15:07
The initial issue you reported with `-DENABLE_TESTING=OFF` has finally been resolved by @robaerd (we internally tracked the bug in #3452).

Could you please verify that the issue is resolved for you? The fix is on master since 4223bf1cbec29f9b7091cd07ebb9f806e8796cb0, but has not yet been released.

**Comment by kraileth** [comment] 2021-04-17 07:24
@mpranj Great! Just resurrected my Solaris machine for the purpose to give this a try. Unfortunately I've run into a broken dependency port on the Solaris platform. So I will need to look into getting that one fixed first.

**Comment by markus2330** [comment] 2021-05-01 05:20
@kraileth thank you so much for trying. Would be interesting how well Elektra works on Solaris. We are also thinking about adding a Solaris build machine.

@mpranj Let's ping here again with the next release.

**Comment by mpranj** [comment] 2021-07-13 08:10
Disabling the bindings tests works since 0.9.6. If any new problems occur, please open a new issue.

**Closed by mpranj** 2021-07-13 08:10 UTC
