### ISSUE TITLE
Elektra-web 1.4

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1892] opened 2018-04-05 16:23 UTC
### Visual Appearance

The web-ui now works well but you can certainly improve some details of the visual appearance:

- [x]  Sometimes the tree does not render (the symbol indicates a part is not collapsed, but it only shows white), this happens:
   - [x] after drag&drop with the last of one keys subkeys
   - [x] after removing the last of one keys subkeys
- [x] the "configure metadata" screen is a mess, please use a proper grid layout
- [ ] when adding a new key: Hint is still not nicely layouted.
- [x] for gray keys, the hover text (like create-subkey) is also gray and barely readable
- [x]  after converting type with losing value, the old value is still displayed (but not after reload)

### Accessibility

- [x] tab not usable in dialogs such as "Delete key system/test/#0/a?" (if tab was used before in tree view)
- [x] please try to work a bit with the UI without using the mouse

### Performance issues

- [x]  on small trees collapsing and opening takes forever
- [x] when quickly entering values of meta data, the text sometimes disappears (and reappears)
- [x] when editing values within large keysets, text sometimes disappears (and reappears)
- [x] Collapsing something again seems to not solve the problem (is the structure still in RAM?)
- [x] when clicking on a value, the value is highlighted (much) faster than the key

### Misfeatures

- [x] Why does Binary disable restrict/remove?
- [x] ~~Why is "Current value" within "metadata?~~ I noticed that when you enter a regex that does not match the current value, you might want to adjust the current value to match the regex. Switching between the metadata dialog and the tree view was quite tedious, so I added the current value field to the metadata dialog.
- [x] What exactly does restrict/null? (you do not allow to enter null keys, do you?)

**Comment by omnidan** [comment] 2018-04-19 09:27
@markus2330 I created a new PR with these fixes: https://github.com/ElektraInitiative/libelektra/pull/1929

---

> when adding a new key: Hint is still not nicely layouted.

what do you mean? it looks fine to me (on my setup?). I also tried resizing the window:

![screen shot 2018-04-18 at 16 15 18](https://user-images.githubusercontent.com/668674/38937580-cc88b05e-4323-11e8-8dec-87a8d1b48ce8.png)

It is aligned in a 2x4 grid and vertically center aligned to the name input field.

---

> after converting type with losing value, the old value is still displayed (but not after reload)

I could not reproduce this. I created a key with string value "123", then converted to checkbox, all the fields instantly changed to a checkbox and the value reset.

If you mean the checkbox value is still displayed when converting back to a string, then this is expected behaviour (converting to string does not result in data loss).

Also, it might have been fixed by my other fixes regarding text disappearing and reappearing (it was an issue with state not being synced properly).

**Comment by markus2330** [comment] 2018-04-19 09:36
>  what do you mean? it looks fine to me (on my setup?). I also tried resizing the window:

Maybe it is a matter of taste but I thought that a small gray hint alone (do net get me wrong: size+color is okay) on more than half of the dialog is misplaced.

@0003088 @tom-wa @beku Maybe you have an idea? You are also welcomed to try out  #1929 and give some usability feedback.

>  I could not reproduce this. I created a key with string value "123", then converted to checkbox, all the fields instantly changed to a checkbox and the value reset.

Did you also test Firefox ESR?

> Also, it might have been fixed by my other fixes regarding text disappearing and reappearing (it was an issue with state not being synced properly).

That is easily possible. It clearly was a synchronization problem (after manual reloading the problem was gone).

**Comment by omnidan** [comment] 2018-04-19 09:47
> Did you also test Firefox ESR?

Yes, I tested everything with Firefox ESR before creating the PR.

**Closed** 2018-05-26 13:17 UTC
