### ISSUE TITLE
jenkins: check_formatting on alpine linux sometimes (?) fails

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2565] opened 2019-03-31 07:41 UTC
https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/550/pipeline/

**Comment by sanssecours** [comment] 2019-03-31 08:51
I think this is a duplicate of issue #2529.

**Closed by sanssecours** 2019-03-31 08:51 UTC
Labels: build, duplicate
