### ISSUE TITLE
OpenBSD 6.0 issues

### ISSUE THREAD

**Issue by tom-wa** [ElektraInitiative/libelektra#1100] opened 2016-11-15 20:38 UTC
ELEKTRA CHECK RESOLVER

Check if script tests the correct version
dump available
grep: unknown option -- m
usage: grep [-abcEFGHhIiLlnoqRsUVvwxZ] [-A num] [-B num] [-C[num]]
        [-e pattern] [-f file] [--binary-files=value] [--context[=num]]
        [--line-buffered] [pattern] [file ...]
skipping test because plugin variant x is missing, for x with app/config_file
.....
check_resolver RESULTS: 32 test(s) done 46 skipped 0 error(s).

kdb testmod_network
   ICONV   TESTS
====================

/home/thomas/libelektra/src/plugins/network/testmod_network.c:27: error in test_addr: could not check ipv4 addr
/home/thomas/libelektra/src/plugins/network/testmod_network.c:41: error in test_addr: could not check ipv4 addr
/home/thomas/libelektra/src/plugins/network/testmod_network.c:62: error in test_addr: could not check ipv6 addr
/home/thomas/libelektra/src/plugins/network/testmod_network.c:76: error in test_addr: could not do addr check (without specifying ipv4/ipv6)
/home/thomas/libelektra/src/plugins/network/testmod_network.c:83: error in test_addr: could not do addr check (without specifying ipv4/ipv6)

test_backendhelpers RESULTS: 14 test(s) done. 5 error(s).

**Comment by markus2330** [comment] 2016-11-15 20:41
This is a duplicate of #654

**Closed by markus2330** 2016-11-15 20:41 UTC

**Comment by tom-wa** [comment] 2016-11-15 20:53
sorry, should have checked the other openbsd issues first.
what about the check_resolver issue ?

**Comment by markus2330** [comment] 2016-11-15 21:05
> what about the check_resolver issue ? 

What do you mean? (Please always link to commit or issue)

If you mean the `~` issue: It worked locally but not on the build server:
http://build.libelektra.org:8080/job/elektra-incremental/1261/console
Fix is welcome!

If you mean the #693, did not look into it, but will do now.

**Comment by tom-wa** [comment] 2016-11-15 21:12
i initially planed on using this issue to collect all openbsd problems i can find.

i meant that one: 

ELEKTRA CHECK RESOLVER

Check if script tests the correct version
dump available
grep: unknown option -- m
usage: grep [-abcEFGHhIiLlnoqRsUVvwxZ] [-A num] [-B num] [-C[num]]
[-e pattern] [-f file] [--binary-files=value] [--context[=num]]
[--line-buffered] [pattern] [file ...]
skipping test because plugin variant x is missing, for x with app/config_file
.....
check_resolver RESULTS: 32 test(s) done 46 skipped 0 error(s).

**Comment by markus2330** [comment] 2016-11-15 21:27
Seems to be a new problem, can you create a PR to fix it (simply remove `-m` and have a `head` afterwards)?
