### ISSUE TITLE
Web Page Issues

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1030] opened 2016-10-19 14:26 UTC
- [x] When going to Documentation -> Plugins you see the resolver README.md not the intro to plugins. (for decisions it works fine, the name "README" in the top left should be changed though)
- [x] the left menu for plugins and man pages is much too long. Can we make the left menu more compact?
- [x] is there an URL for pages in the left menu?
- [x] markdown converter: is this CAPITALIZATION for headers really necessary?
- [x] C-Code and ini files look funny. (no newlines,...)
- [x] cryptograhic_key_h.. goes across its box (decisions)
- [x] Libraries empty (README.md missing)
- [x] left menu: cursor does not change (as it usually does over links)?
- [x] external links in menus not recognisable (put some sign before them?)
- [x] breadcrumbs need i18n keys in the language file
- [x] plugin readmes look stupid, maybe we should reformat the info block at the top to a code-block?
- [x] images and links in the documentation texts cause trouble
- [x] maybe add a button to "jump to top"?
- [x] function `makePrettyName(name)` that is used to format the file name for the menu needs improvements
- [x] markdown for tables doesn't seem to work, although it is explicitely turned on
- [x] some headlines don't look good, maybe change font
- [x] `no-referrer` in links
- [x] sitemap
- [x] autocomplete for snippet fields
- [x] support html5 urls (no hash in URL, which is better for SEO)
### Plugins
- [x] `src/plugins/*/README.md`
  - should always have a short-description in the same line as `infos/description` and a more comprehensive description starting on a new line
  - headlines should have a uniform style, e.g. first-capitalize and not all-upper-case, and also no h1 headlines
  - need to add info about `elektraTemplateCheckConfig()`
- [x] `src/plugins/hosts/README.md` has unparsable headers (seems to be a missing space after #)
- [x] `src/plugins/resolver/README.md`
  - the description headline should start in a new line (only short description inline)
  - the macros at the bottom are considered markdown by github and should be formatted as codeblock maybe
- [x] `src/plugins/wresolver/README.md` the macro causes format problems
- [x] `src/plugins/tcl/README.md` could be improved, almost no info there
- [x] `src/plugins/ini/README.md` has unnecessary indentation in the multiline example?
- [x] `src/plugins/yajl/README.md` has unnecessary indentation in the examples?
- [x] `src/plugins/fstab/README.md` could use code-blocks for inline code
- [x] `src/plugins/regexstore/README.md` either give a list of TODOs at the bottom or remove the hint; plugin status is `unfinished` anyway
- [x] `src/plugins/simpleini/README.md` reformat HEADER (add space after #)
- [x] `src/plugins/cachefilter/README.md` put description with a headline into new line
- [x] `src/plugins/keytometa/README.md`
  - indentation of examples
  - code blocks for elektra keys?
- [x] `src/plugins/struct/README.md` indentation of example code like `src/plugins/glob/README.md`
### Libraries
- [x] `src/libs/README.md` uses absolute paths
### Other
- [x] `doc/COMPILE.md` could need some improvements too (e.g. `CMAKE_INSTALL_PREFIX/include/elektra` formatted as code block for better readability)
## Snippets
- [x] Scope/Slug is not explained. And is it a good idea to make it required entries?
- [x] edit entry does not work after only changing "Configuration:"
- [x] Rank in account information without explanation?

**Comment by Namoshek** [comment] 2016-10-19 14:47
> When going to Documentation -> Plugins you see the resolver README.md not the intro to plugins. (for decisions it works fine, the name "README" in the top left should be changed though)

What would you expect to see?
Decisions is of type `listfiles` (list files of directory), while plugins is of type `parsereadme` (which obviously only shows readme content). Maybe the latter needs some way to define additional content / files (what order to use then for the files after merge)?

>  the left menu for plugins and man pages is much too long. Can we make the left menu more compact?

Definitely going to change it. As I said, I haven't made much design changes yet... it is all plain bootstrap and I used elements that were available / easy to use.

> is there an URL for pages in the left menu?

Currently not, but I can see if this is possible.

> markdown converter: is this CAPITALIZATION for headers really necessary?

What do you mean?

> C-Code and ini files look funny. (no newlines,...)

Maybe we need to format them in markdown syntax (during copy-website-content), so they are shown as code blocks. Or we use some other styling tool for files with a file-extension unequal to `.md`. So files without extension and `.md` files are considered markdown, all other files are considered code files..?

> left menu: cursor does not change (as it usually does over links)?

There is no `href` tag, so I need to set it manually via `cursor: pointer;`. Will do so as part of design changes.

---

> Scope/Slug is not explained. And is it a good idea to make it required entries?

I cannot leave them empty, sorry. I can change the placeholder to something like "in case of uncertainty, use 'default'". 
I also thought about generating the slug from the title (basically `title.toLowerCase().replace(' ', '-')` like many websites do it for the URL), but offer a manual change option in case an entry already exists.

> edit entry does not work after only changing "Configuration:"

The reason is that the format is not chosen by default (should be the upload format of the entry). I think it is because I changed the API response slightly, which I forgot to change here. Ty.

> Rank in account information without explanation?

I'll replace it by the i18n key I have already created for the ranks, then it will be something like `Administrator (100)`.

---

Thanks for the nice feedback!

**Comment by markus2330** [comment] 2016-10-19 15:27
> What would you expect to see?

The README.md itself. This can be hardcoded for this type of pages.

> What do you mean?

lol, sorry, my fault. Seems like that augeas/README.md actually had everything in upper case letters. I opened #1031 for that. But that all the code examples are not formatted on the augeas plugins page is an issue of the markdown parser. Lines beginning with a tab should be code.

> Maybe we need to format them in markdown syntax (during copy-website-content), so they are shown as code blocks. Or we use some other styling tool for files with a file-extension unequal to .md. So files without extension and .md files are considered markdown, all other files are considered code files..?

Considering them source files sounds like a good plan! Is there some highlighter that has good heuristics and also supports config files?

> I cannot leave them empty, sorry. I can change the placeholder to something like "in case of uncertainty, use 'default'". 

Maybe having "default" as default text there would be already ok.

**Comment by Namoshek** [comment] 2016-10-19 16:02
For syntax highlighting, I've chosen [highlight.js](https://highlightjs.org/) because it can easily be used with the markdown parser. There is a wide variety of styles available (color schemas), so we can switch if we find some issues. Changes are not pushed yet.

**Comment by markus2330** [comment] 2016-10-19 16:05
That is great if the code snippets in the markdown files have the same highlighting as individual files!

**Comment by Namoshek** [comment] 2016-10-19 16:16
> But that all the code examples are not formatted on the augeas plugins page is an issue of the markdown parser. Lines beginning with a tab should be code.

Yes, seems to be an issue of the parser, doesn't seem easy to influence/change (couldn't find any setting or info about it). I think an easy and acceptable fix would be to replace tabs with four spaces during collection of website files. What do you think?

**Comment by Namoshek** [comment] 2016-10-19 16:55
I updated the frontend, I think it makes a much better impression now.

Some things I've noticed:
- [ ] `hosts` plugin README.md has unparsable headers (seems to be a missing space after #)
- [ ] breadcrumbs need i18n keys in the language file
- [ ] plugin readmes look stupid, maybe we should reformat the info block at the top to a code-block?
- [ ] images and links in the documentation texts cause trouble
- [ ] maybe add a button to "jump to top"?
- [ ] function `makePrettyName(name)` that is used to format the file name for the menu needs improvements
- [ ] markdown for tables doesn't seem to work, although it is explicitely turned on

**Comment by Namoshek** [comment] 2016-10-20 06:22
I added some docu issues I noticed, we can also open a separate issue for that if you want.

**Comment by markus2330** [comment] 2016-10-20 07:00
> Yes, seems to be an issue of the parser, doesn't seem easy to influence/change (couldn't find any setting or info about it). I think an easy and acceptable fix would be to replace tabs with four spaces during collection of website files. What do you think?

Is there some kind of markdown validator? We are currently use at least 5 different markdown converters (qt-gui uses discount, doxygen markdown, man pages with ronn, github, and yours) and the results between the converters are not reliable at all. Maybe we reduce to some subset every Parser understands?

What about reporting a bug? The tab feature is clearly mentioned on the original markdown homepage.

> I updated the frontend, I think it makes a much better impression now.

Yes, plugins is much nicer!

> I added some docu issues I noticed, we can also open a separate issue for that if you want.

Thanks for adding. If you can fix them, you can leave them here.

**Comment by Namoshek** [comment] 2016-10-20 07:18
> Is there some kind of markdown validator?

Not sure. I found two common markdown parsers for web apps, [Marked](https://github.com/chjj/marked) and [Showdown](https://github.com/showdownjs/showdown). Marked seemed easier to use (also with syntax highlighting addition), so I chose this one. Showdown seems to support leading tabs for code blocks, as an example. If you want, I can try showdown as well and see if it supports more features, but I'm not sure how syntax highlighting can be done there (maybe directly on `<code>` blocks).

> What about reporting a bug? The tab feature is clearly mentioned on the original markdown homepage.

Yes, I also looked it up because somewhere I read something about 4 spaces only. I could file a bug report, good idea!

> Thanks for adding. If you can fix them, you can leave them here.

I can clearly fix them, but should it be a separate PR? I think it will be quite some changes, I haven't reviewed all files completely so far.

**Comment by markus2330** [comment] 2016-10-20 07:22
>  If you want, I can try showdown as well and see if it supports more features

Please try to report the bug first. (Unless you already have good reasons that the other project actually is better.)

> I can clearly fix them, but should it be a separate PR?

Thank you! Yes, please a separate PR.

**Comment by Namoshek** [comment] 2016-10-20 07:54
> Please try to report the bug first. (Unless you already have good reasons that the other project actually is better.)

I tried to reproduce it with only the `marked` package (without the angular binding) and it works there. So either I'm doing something wrong or it is the binding that causes trouble. But I think it is no problem to run the tab-replace during content collection, it works well on the website and that is what counts.

> Unless you already have good reasons that the other project actually is better.

Both have pros and cons. :+1:

**Comment by Namoshek** [comment] 2016-10-21 08:24
# Compile #

## Dependencies ##

For the base system you only need cmake and build-essential (make, gcc,
some unix tools).

To build documentation you need doxygen, graphviz and [ronn](https://github.com/rtomayko/ronn/blob/master/INSTALLING#files).

To build pdf documentation you need pdflatex with

    texlive-fonts-recommended
    texlive-latex-recommended
    texlive-latex-extra

For the debian package, please refer to debian/control (in the debian
branch).

For the plugins, please refer to the README.md of the respective plugin.

## Preparation ##

Elektra uses cmake.
Tested are cmake version 2.8.9 and version 3.0.2.

To configure Elektra graphically (with curses) run (`..` belongs to command):

    mkdir build && cd build && ccmake ..

and press 'c' to configure the cache. After applying the desired settings, 
press 'g' to generate the make file.


All options described here, can also be used with cmake rather than
ccmake (`..` does also here belong to the command):

    mkdir build && cd build && cmake -D<OPTION1>=<VAR1> -D<OPTION2>=<VAR2> ..

For information what you can use as `OPTION1` and `OPTION2`, see above.
Note: You have to enclose a value with quotes `""` if it contains a semicolon `;`.
E.g.:

    cmake -DPLUGINS="dump;resolver;yajl" ..

Some scripts in the folder of the same name may help you running cmake.

### Compilers ###

For supported compilers have a look at the automatic build farm on
http://build.libelektra.org:8080/

Additionally, gcc 4.6 armhf is tested regularly.


|   Compiler        |         Version             |      Target       |
|-------------------|-----------------------------|-------------------|
|      gcc          | gcc (Debian 4.7.2-5) 4.7.2  |      i386         |
|      gcc          | gcc (Debian 4.7.2-5) 4.7.2  |      amd64        |
|      gcc          | gcc 4.8                     |      amd64        |
|      gcc          | gcc 4.9                     |      amd64        |
|      gcc          | (Debian 4.4.5-8) 4.4.5      |      amd64        |
|      gcc          | (Debian 4.4.5-8) 4.3        |      amd64        |
|      gcc          | 4.6                         |      armhf        |
|      mingw        | 4.6                         |      i386         |
|      clang        | version 3.5.0-1~exp1        |x86_64-pc-linux-gnu|
|      icc          | 14.0.2 20140120             |x86_64-pc-linux-gnu|
|      gcc/g++      |                             | openbsd 4.9.3 (*) |

> (*) OpenBSD ships an old version of GCC per default, which can not compile Elektra.
> A manual installation of egcc/eg++ is required. Note that not every OpenBSD
> mirror provides the eg++ package. Elektra builds are confirmed with
> egcc/eg++ 4.9.3 in OpenBSD 5.9.
> The packages are called gcc and g++.
> Compile with `CC=/usr/local/bin/egcc CXX=/usr/local/bin/eg++`.

To change the compiler, use cmake settings `CMAKE_C_COMPILER` and `CMAKE_CXX_COMPILER`.

To use gcc-4.3 for example

    cmake -DCMAKE_C_COMPILER=gcc-4.3 -DCMAKE_CXX_COMPILER=g++-4.3 ..

To change the compiler with ccmake, you may need to toggle advanced options (key 't').

### Options ###

Some options, i.e. `PLUGINS`, `BINDINGS` and `TOOLS` are either:

- a list of elements separated with a semicolon (`;`)
   (note that shells typically need `;` to be escaped)
- a special uppercase element that gets replaced by a list of elements, that are:
  - `ALL` to include all elements (except elements with unfulfilled dependencies)
  - `NODE` to include all elements without dependencies
- elements prefixed with a minus symbol (`-`) to exclude an element

Examples for this are especially in the subsection `PLUGINS` below, but they work in the
same fashion for `BINDINGS` and `TOOLS`.

#### Plugins ####

Read about available plugins [here](/src/plugins/).

Because the core of elektra is minimal, plugins are needed to
actually read and write to configuration files (storage plugins),
commit the changes (resolver plugin, also takes care about how
the configuration files are named) and also do many other
tasks related to configuration.

The minimal set of plugins you should add:
- [dump](/src/plugins/dump) is the default storage.
  If you remove it, make sure you add another one and set
  `KDB_DEFAULT_STORAGE` to it.
- [resolver](/src/plugins/resolver) is the default resolver.
  If you remove it, make sure you add another one and set
  `KDB_DEFAULT_RESOLVER` to it.
- [sync](/src/plugins/sync) is very useful to not lose any data.
  If you do not want to include it, make sure to set
  `/sw/elektra/kdb/#0/current/plugins` to a value not containing sync
  (e.g. an empty value).
  See [kdb-mount(1)](/doc/help/kdb-mount.md).

By default nearly all plugins are added. Only experimental plugins
will be omitted:

    -DPLUGINS="ALL;-EXPERIMENTAL"

To add also experimental plugins, you can use:

    -DPLUGINS=ALL

Note that plugins get dropped when dependencies are not satisfied.
To add all plugins except some plugins you can use:

    -DPLUGINS="ALL;-plugin1;-plugin2"

E.g. if you want all plugins except the jni plugin you would use:

    -DPLUGINS="ALL;-jni"

To add all plugins not having additional dependencies
(they need only POSIX), you can use

    -DPLUGINS=NODEP

Note, that every `infos/provides` and `infos/status` field written uppercase can
be used to select plugins that way.  You also can combine any of these fields
and add/remove other plugins to/from it, e.g. to include all plugins without deps,
that provide storage (except `yajl`) and are maintained, but not include all plugins
that are experimental, you would use:

    -DPLUGINS="NODEP;STORAGE;-yajl;MAINTAINED;-EXPERIMENTAL"

The inclusion is determined by following preferences:

1. if the plugin is explicit excluded with `-plugin`
2. if the plugin is explicit included with `plugin`
3. if the plugin is excluded via a category `-CATEGORY`
4. if the plugin is included via a category `CATEGORY`
5. the plugin is excluded if it is not mentioned at all

Note, that changing `PLUGINS` will not modifiy the defaults used
after Elektra was installed.  For this endeavour you need to change:

    -DKDB_DEFAULT_RESOLVER=resolver

and

    -DKDB_DEFAULT_STORAGE=dump

The default resolver and storage will write to `KDB_DB_FILE` and `KDB_DB_INIT`
([for bootstrapping](/doc/help/elektra-bootstrapping.md)).

Obviously, you can pass the exact list of plugins you want, e.g.:

    -DPLUGINS="resolver;sync;dump"

Some plugins are compile-time configureable. Then you can choose which
features are compiled in or out. This is especially important in the
bootstrapping phase, because then only the compiled in configuration
applies. To compile-time-configure a plugin, you just pass a underscore
(_) and flags after the name of the plugin.

The resolver for example distinguish between 3 different kind of flags:

    -DPLUGINS="resolver_baseflags_userflags_systemflags"

Following baseflags are available:

- `c` for debugging conflicts
- `f` for enabling file locking
- `m` for enabling mutex locking

The user flags are (the order matters!):

- `p` use passwd/ldap to lookup home directory using `getpwuid_r`
- `h` use the environment variable HOME
- `u` use the environment variable USER
- `b` use the built-in default cmake variable `KDB_DB_HOME`

The system flags are (the order matters!):

- `x` use the environment variable `XDG_CONFIG_DIRS`
  (`:` are interpreted as part of filename, no searching is done!)
  This option is not recommended (unless for testing), because it
  allows users to fake system configuration.
- `b` use the built-in default cmake variable `KDB_DB_SYSTEM`
- note: if a path that begins with / is chosen, the system flags are irrelevant
  and the path is taken as-is.

E.g. one may use:

    -DPLUGINS="resolver_lm_uhpb_b"

To add `resolver_l_h_b` you need to specify

    -DPLUGINS="resolver;resolver_l_h_b"

You can add resolver with any combination of the flags, even if they are
not available in `ALL`.

#### Tools ####

Tools are used to add extra functionality to Elektra.
The flag used to specify which tools are compiled is
`-DTOOLS`, thus flag works similarly to the `-DPLUGINS` flag,
but is more limited in its functionality (which does not
matter, because there are not so many tools).

To add all tools, you can use::

    -DTOOLS=ALL

To add all tools except of race, you can use:

    -DTOOLS="ALL;-race"

To specify specific tools you can use, e.g.:

    -DTOOLS=qt-gui;kdb


#### Bindings ####

Bindings are used in the same way as `TOOLS`.
For example you can use:

    -DBINDINGS=ALL

Note that the same languages are sometimes available over GI and SWIG.
In this case, the SWIG bindings are preferred.
The SWIG executable my be specified with:

    -DSWIG_EXECUTABLE=...

If this option is not used, cmake will find the first occurrence of
`swig` in your environment's path.
Per default GI bindings are not included.
To include them, use:

    -DBINDINGS="ALL;GI"

Some bindings provide different APIs (and not a different language), e.g:

- `gsettings`
- `INTERCEPT` with `intercept_fs` and `intercept_env`

To not add such APIs, but only `swig` bindings and `cpp`, you can use:

    -DBINDINGS=SWIG;cpp


#### CMAKE_BUILD_TYPE  ####

`Debug`, `Release` or `RelWithDebInfo`
See help bar at bottom of ccmake for that option or:
http://www.cmake.org/Wiki/CMake_Useful_Variables

#### ELEKTRA_DEBUG_BUILD and ELEKTRA_VERBOSE_BUILD  ####

Only needed by Elektra developers.
Make the library to output logging information.
It is not recommended to use these options.

#### BUILD_DOCUMENTATION ####

Build documentation with doxygen.
The [kdb](/src/tools/kdb) tool does only have the integrated docu at the moment.

#### CMAKE_INSTALL_PREFIX ####

`CMAKE_INSTALL_PREFIX` defaults to `/usr/local`.
So by default most files will installed below `/usr/local`.
Exceptions to this are files handled by [INSTALL_SYSTEM_FILES](#install_system_files).

Edit that cache entry to change that behavior.
Also called system prefix within the documentation.

If you want to create a package afterwards it is ok to use
paths that you can write to (e.g. `-DCMAKE_INSTALL_PREFIX=/home/username/`)

#### LIB_SUFFIX ####

Lets you install libraries into architecture specific folder.
E.g. for 32/64 bit systems you might install libraries under
`lib64`. Set `LIB_SUFFIX` to `64` to achieve exactly that.
So the system library folder will be `CMAKE_INSTALL_PREFIX/lib64`
then.

#### TARGET_INCLUDE_FOLDER ####

By default include folders will be installed below
`CMAKE_INSTALL_PREFIX/include/elektra`.
This entry let you change the elektra.
If the entry is empty, the include files will be
installed directly to `CMAKE_INSTALL_PREFIX/include`.

#### TARGET_PLUGIN_FOLDER ####

Similar to above, but with the plugins. Default is:
`CMAKE_INSTALL_PREFIX/lib${LIB_SUFFIX}/elektra`
It can be also left empty to install plugins next
to other libraries.

#### GTEST_ROOT ####

Specifies the root of the GoogleTest sources, to be used
for some of the tests. A `CMakeLists.txt` inside `GTEST_ROOT`
will be searched as way to detect a valid GoogleTest source
directory.
If it is empty (`""`), an internal version of gtest will be used.

It is recommended that you browse through all of the options using ccmake.
Afterwards press 'c' again (maybe multiple times until all variables are
resolved) and then 'g' to generate.  Finally press 'e' to exit.

#### INSTALL_BUILD_TOOLS ####

Specifies that the build tools, i.e. `elektra-export-symbols` and `elektra-export-symbols`
are installed (by default off). Is needed for cross-compilation.

#### INSTALL_SYSTEM_FILES ####

Some of Elektras targets require to be installed into specific folders in the
file system hierarchy to work properly.

This variable is enabled by default but requires the install target to have the
rights to write into the corresponding folders. Set `-DINSTALL_SYSTEM_FILES=OFF`
if you do not need any of them.

If you do not have root rights you can copy them manually to your user folder.

Currently the installed system files are as following:

|   Module        |         Description             |      Install Path                      |
|-----------------|---------------------------------|----------------------------------------|
| bash-completion | bash tab auto completion file   | `completionsdir` from pkg-config (*)   |
| zsh-completion  | zsh tab auto completion file    | /usr/share/zsh/vendor-completions      |
| GIR             | introspection file for bindings | `INTROSPECTION_GIRDIR` from pkg-config |
| GSettings       | GSettings backend module        | `GIO_MODULE_DIR` from pkg-config       |


(*) Or `/usr/share/bash-completion/completions` as fallback.

#### ENABLE_OPTIMIZATIONS ####

In order to keep the binaries as small as possible this flag allows to trade memory for speed.

## Building ##

### Without IDE ###

To build the source use:

    make

You can pass:
- `-j` for parallel builds
- `VERBOSE=1` to see the invocations of the compiler

### With CodeBlocks ###

You can build Elektra using Code::Blocks under Gentoo:

Precondition:
Make sure you have a compiler, xml2 (for kdb tool) and xsl (see later) installed. 
cmake configure will help you with that, it will make sure you don't forget something
essential.

For Most Linux system all you have to do is open up a console and

    mkdir build
    cd build
    cmake .. -G 'CodeBlocks - Unix Makefiles'
    make package

Note  1:
    You can use other editor if you like just type cmake at the
    console to get a list of option you can pass to cmake as long as well
    as a list of what code editor project cmake can create.

Note 2:
    For Unix if you have nCurses install you can run ccmake to set important option after
    running cmake like to enable debug symbol.

Note 3:
    for Gentoo is recommend to emerge sys-apps/lsb-release to name the package
    right even thou not required.

**Comment by markus2330** [comment] 2016-10-22 18:23
I added two items in the list above (I assume you do not get notifications from github when I edit the field?):

- no-referrer in links
- sitemap

Btw. do you automatically use https links if the site is delievered via https?

**Comment by markus2330** [comment] 2016-10-22 20:43
> What do you think of adding a global tag like explained in this post? This will also remove tracking information for other requests (in browsers that support it).

Do you mean implementing both or only a global tag? The global tag should be enough if it is non-trivial to add it to every link.

> [sitemap] Have to look into this. I thought they are nowadays not really used anymore because crawlers are finally good enough and don't need them anymore. But if it is necessary, I'll see what I can do.

Thanks, smaller search engines might still heavily rely on it. Supporting changefreq and priority seems to be not so important.

> Dynamicly created pages (e.g. details of an entry) can't be part of it though, I think that's clear.

Do you mean you also cannot add the snippets in the sitemap?

> Links that do not leave the website are only state-transitions, i.e. no real hard-links. Fetching the content of pages, which happens in the background, will be done via https in this case then. Angular is intelligent enough to do so.

Ok, nice!

**Comment by Namoshek** [comment] 2016-10-23 07:28
> Do you mean implementing both or only a global tag? The global tag should be enough if it is non-trivial to add it to every link.

I mean to only add a global tag instead of tagging every link, which is not so easy, because I'm using links in quite some places already (and not all are HTML links, the Report on GitHub button for example is implemented code-based, which makes it even more difficult).

> Thanks, smaller search engines might still heavily rely on it. Supporting changefreq and priority seems to be not so important.

Yeah, you are right.

> Do you mean you also cannot add the snippets in the sitemap?

Sorry, I guess what I wrote was a bit misleading. I can certainly add dynamic pages like the docu from the structure file (because that basically is already a sitemap), but I don't think I can add pages for the content of the backend. Other pages with big databases create the sitemap by appending, but that won't work here because backend and frontend are split apart. I can try to add sitemap creation also for dynamic pages during website-content creation, but I can't promise anything.

Btw. you are talking about a sitemap.xml, right? Not one visible for the users in the frontend?

**Comment by markus2330** [comment] 2016-10-23 09:15
> I mean to only add a global tag instead of tagging every link, which is not so easy, because I'm using links in quite some places already (and not all are HTML links, the Report on GitHub button for example is implemented code-based, which makes it even more difficult).

Then a global tag it is!

> Sorry, I guess what I wrote was a bit misleading. I can certainly add dynamic pages like the docu from the structure file (because that basically is already a sitemap), but I don't think I can add pages for the content of the backend. Other pages with big databases create the sitemap by appending, but that won't work here because backend and frontend are split apart. I can try to add sitemap creation also for dynamic pages during website-content creation, but I can't promise anything.

Maybe the sitemapindex and having two different sitemaps helps? The sitemap of snippets basically would be a search for all snippets.

> Btw. you are talking about a sitemap.xml, right? Not one visible for the users in the frontend?

Of course. In the website every page is reachable by the menu, so a sitemap would not give much benefits to a user, would it?

**Comment by Namoshek** [comment] 2016-10-23 10:08
> The sitemap of snippets basically would be a search for all snippets.

The problem is that search results are limited too 200, meaning it can take several requests...

**Comment by markus2330** [comment] 2016-10-23 11:02
Thanks for considering all these points, I know it really adds up to a lot of effort.

But to get the best out of your efforts: 200 seems to be arbitrary. Which purpose has this limitation at all? With a bit generalized search (e.g. have tags in "Entry Preview") it might be easily possible to provide real-time suggestions, sitemap and search functionality: everything with the same API.

Argumentations about performance please only with benchmarks. With cppcms and in-memory requests the queries must be really complicated to cause overhead. E.g. iterating over 40200 keys takes about 100 Microseconds, see 7a54d33c26cdc63de80d6317fa011d0d74838a88

I understand that both real-time suggestions and "dynamic" sitemaps are considerable new effort, so I won't persist on it (can be done later or other solutions are possible, too). But please consider:

1. several people argued that they would expect real-time suggestions and they might really help a lot in data consistency and reduction of time effort to submit a snippet.
2. being found via web searches might be crucial for our service to be found at all.

Nevertheless, both features are clearly not a part of #1033 so there is no urge to decide anything now.

**Comment by Namoshek** [comment] 2016-10-23 11:43
> But to get the best out of your efforts: 200 seems to be arbitrary. Which purpose has this limitation at all?

The limitation is more a protection (and at the same time the default value for the number of rows being returned if no parameter is set). I doubt that the iteration of keys will be the bottleneck, but rather everything around it, starting from splitting keys over building the response to sending it. 

Theoretically we could just increase the currently defined row limit to one million (or whatever) without changing any code at all. For the search the frontend is using pagination anyway, so this should be no harm. In case something happens, we could still define another cap.

> With a bit generalized search (e.g. have tags in "Entry Preview") it might be easily possible to provide real-time suggestions, sitemap and search functionality: everything with the same API.

It would provide at least enough data to offer all these features, that's right. Constructing the proper data structures from the generalized response in the browser might not be the best idea though.

I think it is not too much effort to implement both suggestions, but I think I'll take some more days for them, because I got other stuff going on first.

**Comment by Namoshek** [comment] 2016-10-25 17:46
I implemented both features, let me hear what you think. I have not tested it with huge data yet, only with what is in the database so far.

I'm also aware of the small design mistake I made, the entry form has overlapping icons on some input fields. Have to think about how to fix first (maybe moving the question mark to somewhere else...). It comes because I changed the validation somewhat, so that the validation icon is in the input field.

**Comment by markus2330** [comment] 2016-10-31 13:44
Thank you, looks nice. @krit0n can you look at the webpage and look if you find some usability problems?

**Comment by Namoshek** [comment] 2016-11-02 21:25
I think it is too difficult to make the plugin sections expandable, I tried around a bit, but without changing the output of the structure generator (which is not easy) it won't work. Can we wait for feedback of users and change this later if necessary (maybe together with some other things)?

**Comment by markus2330** [comment] 2016-11-02 21:36
Strange, I thought that would be an easy js task. Yes, it can wait.

Note that there is now a README.md in doc/tutorials so it can be handled in the same way as plugins (expending sections won't be necessary here, though)

**Comment by Namoshek** [comment] 2016-11-02 22:06
I think we need to add some more stuff to the "Getting started" sections too, they seem very empty. I'm going to give this a shot tomorrow.

Btw. I added news to the sitemap and implemented a very basic RSS creation task, which basically creates exactly the same output than your old script. The output path for the html files can be changed manually as well, but I think I should add support for absolute paths.

**Comment by Namoshek** [comment] 2016-11-03 15:30
I added some more pages to the "getting started" sections and I changed the tutorials and decisions to be based on their README.md.

The biggest change is the main page though, which has now some content. Let me hear what you think of it (I could imagine you miss some colors... :smile:).

**Comment by markus2330** [comment] 2016-11-03 16:20
> "getting started"

It is getting nice! I am somehow missing a link from "getting started" to tutorials. Do you have an idea how we can achieve this (adding links at the end of the documents?)

> changed the tutorials

Great! But why are the "intercept" documents external links? They should point to something within the docu. Can you add them to the side bar of tutorials, too?

> main page

Very nice first attempt. I wonder why you made it so compact? The example web site you told about had much more white space in between. The content needs some improvements though, we definitely do not only want "sophisticates" to use Elektra ;) "Symbolic links" is a rather special feature, the core idea is that we allow the user/admin/programmer to specify how the access is done. Is "Want to see how it works?" empty?

**Comment by Namoshek** [comment] 2016-11-03 16:44
> It is getting nice! I am somehow missing a link from "getting started" to tutorials. Do you have an idea how we can achieve this (adding links at the end of the documents?)

Should be no problem, I've already implemented the "staticlink" type. Will add this with the next version then.

> Great! But why are the "intercept" documents external links? They should point to something within the docu. Can you add them to the side bar of tutorials, too?

Hmm, the reason seems to be that these links are absolute, which I thought we do not use. I'll see that I implement support for it.

> Very nice first attempt.

Thanks, that's all I wanted to hear. :smile: 

>  I wonder why you made it so compact? 

The laravel website plays a lot with colors and images. I think if we put too much white space in there without adding colors/images, it will look aweful. We could try to optimize it to have only the key facts on the screen without scrolling (not the video below) - but we need to know what resolution to optimize for then.

Another problem might be that it doesn't look exactly the same on different devices (because of the font which is not available on every OS). I haven't found a nice web-font that all common OS have installed...

> The content needs some improvements though

Absolutely, I never expected it to be perfect. Concrete suggestions are definitely welcome!

> Is "Want to see how it works?" empty?

No, I embedded the asciinema player with the video (maybe we record another video without typos and a concept?). I guess it is your script blocker that doesn't like it.

**Comment by markus2330** [comment] 2016-11-03 17:21
> links are absolute

Yes, that would be great. It would be strange to change the links to something like `../../../`.

> The laravel website plays a lot with colors and images.

Maybe you and @waht  find some way to do so? We will certainly discuss the page in the next meeting!

> I guess it is your script blocker

Yes, that was it. Thanks!

**Comment by Namoshek** [comment] 2016-12-09 09:39
Moved the last open point to #1151 to get rid of the redundant issues.

**Closed by Namoshek** 2016-12-09 09:39 UTC
