### ISSUE TITLE
web-ui: support new namespaces

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2441] opened 2019-02-26 14:02 UTC
## Steps to Reproduce the Problem

Have some default keys and start up Web-UI:

```sh
kdb setmeta /sw/example/highlevel/#0/current/mydouble default 0
kdb ls /
#> /sw/example/highlevel/#0/current/mydouble
kdb run-elektrad
kdb run-web
```

## Expected Result

That Web-UI starts up without issues.

## Actual Result

An error is displayed:

```
KDBError

Command failed: "kdb" ls -0 "sw"
Sorry, I could not process the arguments: sw is not a valid keyname

For absolute keys (starting without '/'), please note that only one of the 
```

## System Information

- Elektra Version: master

**Comment by goJoWe16** [comment] 2019-03-20 17:39
@markus2330 Could you please assign me to this issue for the course CM and unassign me from the issue #2476 as discussed in this the thread of issue #2476?

**Comment by markus2330** [comment] 2019-03-20 17:44
Done!

**Comment by goJoWe16** [comment] 2019-03-27 13:05
@markus2330 

I am not able to reproduce this issue with the current version of elektra. The web-ui starts up without any issues on my system (using one instance):

![Bildschirmfoto von 2019-03-27 14-03-48](https://user-images.githubusercontent.com/17863315/55077992-5f43ad80-5099-11e9-8299-79064deedee5.png)

**Comment by markus2330** [comment] 2019-03-27 17:01
I just see that this issue has overlap with #2408, which already assigned to someone else. I clarified which part should be fixed in which issue.

With #2456 this issue most likely fixes itself. So here actually only a verification step is needed after #2456 was fixed (which hopefully will happen today).

But #2410 will not fix itself, as it needs changes in how `kdb` is executed and is also very much related to this issue. Can you take this over? (I assigned you there.)

**Comment by goJoWe16** [comment] 2019-03-27 17:11
Yes I can take over issue #2410 and will also verify if the fix of issue #2408 fixes this issue. 

Unfortunately, I will only be able to fix issue #2410 until the next deadline in the CM course next week.

**Comment by markus2330** [comment] 2019-03-27 17:46
> Yes I can take over issue #2410 and will also verify if the fix of issue #2408 fixes this issue.

Thank you!

> Unfortunately, I will only be able to fix issue #2410 until the next deadline in the CM course next week.

It would be better if you can fix two issues till then. Until now no PR was accepted.

**Comment by goJoWe16** [comment] 2019-03-27 18:17
Is okay by me, I will try my best!

**Comment by markus2330** [comment] 2019-03-27 20:09
Thank you!

**Comment by goJoWe16** [comment] 2019-04-03 10:32
This issue cannot be reproduced with the description given in this issue, but it can be reproduced following the following steps (based on the descirption of issue #2410):

```
sudo kdb mount `pwd`/LCDd-spec.ini spec/sw/lcdproc/lcdd/#0/current ni
sudo kdb spec-mount /sw/lcdproc/lcdd/#0/current
kdb set '/sw/lcdproc/lcdd/#0/current/curses/background' green
```

This leads to the same KDB error as initially stated in this issue.

![Bildschirmfoto von 2019-04-03 12-31-52](https://user-images.githubusercontent.com/17863315/55472496-886dbc00-560c-11e9-8986-3d3763c67f27.png)

@markus2330 I will try to fix the initial issue for the course CM, i hope that is okay.

**Comment by markus2330** [comment] 2019-04-03 12:22
Yes, it is okay!

Sorry for the incomplete description of how to reproduce the issue.

**Comment by markus2330** [comment] 2019-04-04 09:57
I'll keep it open for now as the workaround might be removed later.

**Comment by markus2330** [comment] 2019-11-19 11:28
New tasks:

- Support new namespaces as introduced in #3102 
- remove workaround

**Comment by mpranj** [comment] 2020-11-24 18:57
Since the keyname overhaul, we need to check the web-ui in general.

**Comment by markus2330** [comment] 2020-11-25 09:13
Yes :sparkling_heart:, I opened #3570 for the various topics we should retest.

**Comment by lukashartl** [comment] 2022-05-21 20:37
`elektrad`, `web-ui` and `webd` received fixes for the namespace problems in

* #4299 
* #4353

I'll close this issue and we will track further issues in:

* #4356

**Closed by lukashartl** 2022-05-21 20:37 UTC
Labels: bug, usability, lang/web, lang/go, project2022s
