### ISSUE TITLE
publish maven artifacts failed

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#4404] opened 2022-07-11 08:14 UTC
## Steps to Reproduce the Problem

Build the release pipeline on Jenkins.

## Expected Result

Success.

## Actual Result

```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/jenkins/workspace/libelektra-release/src/bindings/jna/build.gradle' line: 55

* What went wrong:
Error while evaluating property 'stagingRepositoryId' of task ':closeSonatypeStagingRepository'
> No staging repository with name sonatype created
```

## System Information

- Elektra: master
- Operating System: Ubuntu Focal

## Further Log Files and Output

Full log:
[mvn_log.txt](https://github.com/ElektraInitiative/libelektra/files/9081978/mvn_log.txt)

**Comment by mpranj** [comment] 2022-07-11 08:15
Any ideas why this happens?

I will try to obtain full debug level output and see if there is more information.

**Comment by markus2330** [comment] 2022-07-11 13:06
Commenting out these lines sounds like it cannot harm. Maybe it does not help (if some later code does a similar iteration and also tries to evaluate the property). But it is worth a shot if nobody has a better idea.

@tucek do you have a better idea?

@mpranj did you already try to publish the Kotlin binding? Does it work? (For problems please reply in #4393 unless the issue is related to this one.)

**Comment by mpranj** [comment] 2022-07-12 11:41
Commenting out the logging line as suggested by @kodebach helped, thank you!
Publishing to [maven central](https://search.maven.org/artifact/org.libelektra/libelektra/0.9.10-8/jar) now worked as usual.

I needed to manually rebuild the alpine release image, so i did not yet tag the release on GitHub. It is done now.

I don't know about the Kotlin bindings. Their [docu](https://github.com/ElektraInitiative/libelektra/blob/c9aaac08c74efba2abf529e12467ab6fa480a322/src/bindings/jna/libelektra-kotlin/README.md?plain=1#L6) says that they are not being published yet, at all. Maybe this needs to be updated?

**Comment by markus2330** [comment] 2022-07-12 13:36
Great job! :rocket: 

> Their [docu](https://github.com/ElektraInitiative/libelektra/blob/c9aaac08c74efba2abf529e12467ab6fa480a322/src/bindings/jna/libelektra-kotlin/README.md?plain=1#L6) says that they are not being published yet, at all. Maybe this needs to be updated?

Yes, as far as I know it was not published until now. I updated the text what to do in https://github.com/ElektraInitiative/libelektra/issues/4393. The issue is waiting. :heart_on_fire:

**Comment by markus2330** [comment] 2022-07-12 15:27
I'll close this issue, too. Seems like the problem was in logging code.

Thanks for triaging/fixing it so quickly! :heart:

**Closed by markus2330** 2022-07-12 15:27 UTC
Labels: build
