### ISSUE TITLE
relax calling DBus API without running daemon

### ISSUE THREAD

**Issue by beku** [ElektraInitiative/libelektra#1705] opened 2017-11-21 00:46 UTC
# Steps to Reproduce the Problem

Setup a environment without DBus session :/

# Expected Result

Continue to work, despite of DBus daemon not running :-)

# Actual Result

assert == exit()

# System Information

- Elektra Version: 0.8.20
- Oyranos:master with active make test-2 target in OBS:oyranos.spec

# Further Log Files and Output
OBS with vanilla elektra-0.8.20:
[   98s] ./test2
[   98s] process 24035: arguments to dbus_connection_unref() were incorrect, assertion "connection != NULL" failed in file dbus-connection.c line 2823.
[   98s] This is normally a bug in some application using the D-Bus library.
[   98s]   D-Bus not built with -rdynamic so unable to print a backtrace
[   99s] ./test2-static
[   99s] process 24039: arguments to dbus_connection_unref() were incorrect, assertion "connection != NULL" failed in file dbus-connection.c line 2823.
[   99s] This is normally a bug in some application using the D-Bus library.
[   99s]   D-Bus not built with -rdynamic so unable to print a backtrace
[   99s] [100%] Test liboyranos extensive.

**Comment by beku** [comment] 2017-11-21 08:37
Elektra tests and those of Oyranos in OBS are solved :-)

**Comment by markus2330** [comment] 2017-11-21 12:08
Thank you for reporting the issue!

It seems like cf90b7ef50eb326a283b70656f73f052a56d9a8d introduces cleanup at places which are wrong API use.

@waht Do you have time to test+fix the error cases within dbus? Maybe 401b52e4f7ab58dfd5d3c3142bead712f414b5e9 already fixes all cases, I did not check.

@beku: Should we do a bug fix release for this problem?

**Comment by beku** [comment] 2017-11-21 13:38
To me the dbus_connection_unref (connection) call looks like a clean up from connection = dbus_bus_get (...) . The only case, which is not useful for a dbus_connection_unref(connection) appears to be: if (connection == NULL) ...

So that was maybe a small programming error?

bug fix release?:
I see many warnings from within virtual build/test machines about a missing dbus session. Maybe elektra/dbus and some Xlib related calls have only a problem. But, essentially yes, the main apps shall not crash at all because of such minor issues.

**Comment by markus2330** [comment] 2017-11-21 14:11
> So that was maybe a small programming error?

Yes, it certainly was. Thank you for fixing it!

> I see many warnings from within virtual build/test machines about a missing dbus session.

@waht Can you take a look? (Use dbus plugin without dbus session)

One workaround obviously is to unmount the dbus plugin if no dbus daemon is available but I fully agree that there never should be crashes. And we also should avoid the warnings.

**Comment by waht** [comment] 2017-11-21 19:03
I checked and indeed 401b52e fixed the issue, thank you @beku!

I could not reproduce crashes due to the dbus plugin. I tried `kdb set` on a mountpoint (with the dbus plugin) in the [docker container](https://github.com/ElektraInitiative/libelektra/tree/master/doc/docker) got the warning, but the key was set and exit code was 0.
Maybe the word "assertion" in the message was misleading as [`dbus_connection_unref`](https://dbus.freedesktop.org/doc/api/html/dbus-connection_8c_source.html#l02817) [actually just prints a warning and returns](https://dbus.freedesktop.org/doc/api/html/dbus-internals_8c_source.html#l00931) in case of `connection == NULL`. 

Currently there are no more warnings when using the dbus plugin without a dbus daemon.
The dbus plugin fails silently unless it was compiled with logging enabled of course.

**Comment by markus2330** [comment] 2017-12-21 21:11
Again thanks for reporting and fixing! The fix will be part of the soon-to-come-release.

**Closed by markus2330** 2017-12-21 21:11 UTC
Labels: bug
