### ISSUE TITLE
Website code generation link wrong

### ISSUE THREAD

**Issue by MasterToney** [ElektraInitiative/libelektra#3280] opened 2019-11-25 13:53 UTC
On the website https://www.libelektra.org/home the linke to the code generator https://www.libelektra.org/tools/gen is broken and leads to the first tool https://www.libelektra.org/tools/hub-zeromq
Instead it should be pointed to https://www.libelektra.org/tools/pythongen as the code-generator has recently been renamed.

Is this something that simply needs a redeployment of the website to pick up the changes or a manual change in the source?

**Comment by markus2330** [comment] 2019-11-25 14:16
Can you check if the problem is also on http://a7.libelektra.org/home (a more recent version)?

**Comment by markus2330** [comment] 2019-11-25 14:17
See also #2897

**Comment by MasterToney** [comment] 2019-11-25 20:53
Yes on http://a7.libelektra.org/ the link leads to High-Level API (with code generation)
Should we close this issue as it's fixed in the new version of the website or keep it open till the website gets updated?

**Comment by markus2330** [comment] 2019-11-25 20:56
The website will get updated for the next release manually. And #2897 already tracks the status of automatic website building. So I think we can close this issue if there are no further questions.

**Closed** 2019-11-25 21:00 UTC
Labels: bug, lang/web
