### ISSUE TITLE
augeas: update 1.4.0 to 1.5.0 breaks syntax

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#812] opened 2016-06-24 15:20 UTC
On OS X (homebrew) the augeas package was updated recently. Apparently there were some syntax changes.
Take this also as a hint that travis builds will fail form now on.

```
 30/107 Test  #30: testmod_augeas .....................***Failed    0.01 sec
AUGEAS       TESTS
==================

/Users/mpranj/workspace/libelektra/src/plugins/augeas/testmod_augeas.c:34: error in test_hostLensRead: call to kdbGet was not successful
number: 85
description: : an Augeas error occurred
ingroup: : plugin
module: : storage
at: /Users/mpranj/workspace/libelektra/src/plugins/augeas/augeas.c:414
reason: : Syntax error in lens definition
mountpoint: : user/tests/augeas-hosts
configfile: : /Users/mpranj/workspace/libelektra/src/plugins/augeas/augeas/hosts-read
/Users/mpranj/workspace/libelektra/src/plugins/augeas/testmod_augeas.c:35: error in test_hostLensRead: error in kdbGet
/Users/mpranj/workspace/libelektra/src/plugins/augeas/testmod_augeas.c:39: fatal in test_hostLensRead: ip address of localhost not found
```

@fberlakovich can you take a look if there is an easy fix?

**Comment by fberlakovich** [comment] 2016-06-26 13:51
> @fberlakovich can you take a look if there is an easy fix?

I am busy until Tuesday, but I hope to find some time to look at it next week.

**Comment by markus2330** [comment] 2016-06-27 02:49
What puzzles me is that we only use lenses (in the testcase Hosts.lns) that are distributed with augeas. Can you check if the error also happens if augeas is used directly? Maybe providing augeas version + the lens would help, too.

**Comment by markus2330** [comment] 2016-07-11 16:59
It would be great if you can look into it: it fails every build which makes it cumbersome to check what the status of a PR is.

**Comment by fberlakovich** [comment] 2016-07-11 17:24
The last time I tried I couldn't reproduce it, but I will have another look


________________________________
Von: markus2330 <notifications@github.com>
Gesendet: 11.07.2016 18:59
An: ElektraInitiative/libelektra
Cc: Felix Berlakovich; Mention
Betreff: Re: [ElektraInitiative/libelektra] augeas: update 1.4.0 to 1.5.0 breaks syntax (#812)


It would be great if you can look into it: it fails every build which makes it cumbersome to check what the status of a PR is.

**Comment by markus2330** [comment] 2016-07-11 17:31
Thank you! Maybe you can improve the test cases so that the error message is more useful?

**Comment by fberlakovich** [comment] 2016-07-11 23:41
@mpranj Could you provide the library version that is installed with Augeas 1.5.0 in homebrew? I manually compiled Augeas 1.5.0 on Debian Jessie 8.5 and cannot reproduce the issue. Could it be that your lens file got corrupted?

**Comment by fberlakovich** [comment] 2016-07-11 23:45
Or could you even provide the hosts lens that is used on OS X?

**Comment by markus2330** [comment] 2016-07-12 11:28
Looks like the problem is the current homebrew package. (Based on that Augeas 1.5.0 worked on Jessie without problems.) Is it possible that we continue to use the old homebrew augeas package and report the issue in the homebrew issue tracker?

**Comment by sirblackheart** [comment] 2016-07-12 13:13
I can confirm that
`kdb mount /etc/hosts system/hosts augeas lens=Hosts.lns`
works on Arch Linux with current `augeas 1.5.0` package
while it fails with the same error as in the testcase on OS X with homebrew
```
Error (#85) occurred!
Description: an Augeas error occurred
Ingroup: plugin
Module: storage
At: /tmp/elektra-20160712-40304-8c2ib5/elektra-0.8.17/src/plugins/augeas/augeas.c:414
Reason: Syntax error in lens definition
Mountpoint: system/system/hosts
Configfile: /etc/hosts
```

**Comment by sirblackheart** [comment] 2016-07-13 07:42
I did some further testing. Switching HEAD manually to 1.5.0 taged version of augeas in brews [formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/augeas.rb) also results in working testcases.
So I tried to build and install augeas 1.5.0 from source package which resulted in the known test failure / lens not found.
So it seems 1.5.0 from git which uses `autogen.sh` works, but 1.5.0 from source package which uses `configure` does not.
Hope this info helps.

**Comment by markus2330** [comment] 2016-07-13 11:58
Yes, its one more hint that it is a packaging problem.

We could report it at homebrew. And the easiest workaround would be to use the old augeas package in homebrew.

**Comment by sirblackheart** [comment] 2016-07-13 12:08
Not sure if it is a homebrew packaging problem or a problem in the source package tough.

>  And the easiest workaround would be to use the old augeas package in homebrew.
easy? that would mean we would have to use a custom formula anyhow. homebrew only has versions for some specific packages. so no it is not an easy solution in this case.

**Comment by markus2330** [comment] 2016-07-13 12:18
I saw your fix after writing the message. If you fix works its perfect. It should be still reported to upstream (homebrew) though.

**Comment by sirblackheart** [comment] 2016-07-13 12:28
> It should be still reported to upstream (homebrew) though.

done: https://github.com/Homebrew/homebrew-core/issues/2961

**Comment by markus2330** [comment] 2016-07-13 18:13
Thank you for reporting! I think we can close the issue for now.

**Closed by markus2330** 2016-07-13 18:13 UTC
