### ISSUE TITLE
jna bindings: kdb get shows strange behavior

### ISSUE THREAD

**Issue by e1528532** [ElektraInitiative/libelektra#1258] opened 2017-01-07 16:04 UTC
# Describe what you wanted to do
I corrected a test for the jna bindings which uses kdbGet to open a keyset and then modifies something with kdbSet inspired by the c example of kdbGet at https://www.libelektra.org/examples/kdbget . The relevant code looks like:

	parentKey = Key.create("/sw/tests/jna/1/", Key.KEY_END);
	try (final KDB kdb = KDB.open(parentKey)) {
			final KeySet ks = KeySet.create(10, KeySet.KS_END);
			kdb.get(ks, parentKey);

# Describe what you expected

I expected that this will only fetch keys that live under the specified parentKey /sw/tests/jna/1/key_name/.

# Describe what actually happened

After calling kdbGet, the keyset contained the following elements:
user/kdb_test/1/key_name
user/kdb_test/1/key_name/2
user/test
user/test/bla
user/test/blu

where the last 5 are some keys that i created while playing around with elektra. But as those aren't below the parent key, so why are they included in the keyset after calling kdbGet? As the jna binding basically just calls the c equivalent of kdbGet, this should work? Anything i overlooked here, as i suspect i just got something with keys/namespaces wrong and its not an implementation error of kdbGet?

# System Information

- Elektra Version: master

**Comment by markus2330** [comment] 2017-01-08 08:23
Thank you for reporting the issue!

In #690 we collect points where the default behavior should be changed! In particular the cachefilter fixes the behavior you describe here. In #1078 there are improvements for it, but it depends on the new global hooks implementation @mpranj currently works on.

As workaround for tests (also for some other issues plugins might have), you could mount a new plugin at /sw/tests/jna, unfortunately, there is no C nor JNA API available for mounting, discussion about it next meeting and #1229.

> But as those aren't below the parent key, so why are they included in the keyset after calling kdbGet?

kdbGet (without cachefilter) either fully fetches everything from a plugin or does not (when it already successfully fetched it before)

> As the jna binding basically just calls the c equivalent of kdbGet, this should work?

The other APIs behave in the same way.

> Anything i overlooked here, as i suspect i just got something with keys/namespaces wrong and its not an implementation error of kdbGet?

It is also documented in the C-API of kdbGet (see note). But your view of seeing it erroneous is correct, we should change it (#690).

**Comment by markus2330** [comment] 2017-02-08 17:49
I will close the issue thus it is a duplicate of #690

**Closed by markus2330** 2017-02-08 17:49 UTC
