### ISSUE TITLE
gopts: validation of CLI options not working

### ISSUE THREAD

**Issue by qwepoizt** [ElektraInitiative/libelektra#4029] opened 2021-09-10 15:26 UTC
~~This issue is currently WIP.~~

When using the HL API and the gopts plugin, CLI options passed to the application are not validated.

## 3 classes of validation errors

The following three are not detected:
1. Class 1: missing argument (forked to https://github.com/ElektraInitiative/libelektra/issues/4042)
2. Class 2: wrong type (forked to https://github.com/ElektraInitiative/libelektra/issues/4043)
3. Class 3: validation errors reported by check/* plugins (forked to #4049)

Depending on the causes - which are yet to be identified - this issue should probably be split up into individual issues.

## Steps to Reproduce the Problem

0. Execute the steps below which follow the tutorial [High-level API (with code-generation)](https://www.libelektra.org/tutorials/high-level-api). 

1. Create file test.ini with content:
```
[]
mountpoint = test.ecf

[myboolean]
type = boolean
default = 1
example = 0
opt/long = mb
opt/arg = required

[myenum]
type = enum
check/enum = #1
check/enum/#0 = ok1
check/enum/#1 = ok2
default = ok1
example = ok2
opt/long = me
opt/arg = required

[myfloatcheckrange]
type = float
check/type = float
check/range = 0.0-1.0
default = 1.0
example = 1.0
opt/long = mfcr
opt/arg = required

[mystringcheckdate]
type = string
check/date = ISO8601
check/date/format = timeofday
default = 00:00
example = 01:00
opt/long = mscd
opt/arg = required

[mystringcheckvalidation]
type = string
check/validation = ^[a]{3}$
default = aaa
example = aaa
opt/long = mscv
opt/arg = required

[myunsignedshortcheckrange]
type = unsigned_short
check/type = unsigned_short
check/range = 0-20
default = 10
example = 10
opt/long = muscr
opt/arg = required
```

2. Execute `kdb gen -F ni=test.ini highlevel "/sw/example/myapp/#0/current" conf`

3. Create file myapp.c with content:
```c#include <stdlib.h>
#include <stdio.h>
#include <elektra.h>
#include "conf.h"

int main(int argc, const char * const * argv, const char * const * envp) {
    exitForSpecload (argc, argv);
    ElektraError * error = NULL;
    Elektra * elektra = NULL;
    int rc = loadConfiguration (&elektra, argc, argv, envp, &error);

    if (rc == -1)
    {
        fprintf (stderr, "An error occurred while opening Elektra: %s", elektraErrorDescription (error));
        elektraErrorReset (&error);
        exit (EXIT_FAILURE);
    }

    if (rc == 1)
    {
        // help mode - application was called with '-h' or '--help'
        // for more information see "Command line options" below
        printHelpMessage (elektra, NULL, NULL);
        elektraClose (elektra);
        exit (EXIT_SUCCESS);
    }

    fprintf(stdout, "myboolean is: %d \n", elektraGetMyboolean(elektra));
    fprintf(stdout, "myenum is: %d \n", elektraGetMyenum(elektra));
    fprintf(stdout, "myfloatcheckrange is: %f \n", elektraGetMyfloatcheckrange(elektra));
    fprintf(stdout, "mystringcheckdate is: %s \n", elektraGetMystringcheckdate(elektra));
    fprintf(stdout, "mystringcheckvalidation is: %s \n", elektraGetMystringcheckvalidation(elektra));
    fprintf(stdout, "myunsignedshortcheckrange is: %d \n", elektraGetMyunsignedshortcheckrange(elektra));
    fprintf(stdout, "elektraGet...() was executed for all keys available in specification!\n");
}
```

4. Link and compile

`` cc -g -O0 myapp.c conf.c `pkg-config --cflags --libs elektra-codegen` -I. -o myapp -Wl,-rpath `pkg-config --variable=libdir elektra-codegen` ``

5. Mount specification file and spec-mount via generated `conf.mount.sh`:
``$  APP_PATH=`pwd`/myapp sh conf.mount.sh``

### kdb set - works
When `kdb set` is used all three classes of validation errors are properly detected. No examples here for sake of brevity.

### CLI options - don't work
When the keys are set by passing CLI options to `myapp`, the validation errors are not detected. The actual behavior depends on the class of the error.

#### Class 1: missing argument
1. Execute ` ./myapp --mb` (--mb can be replaced by any other option, e.g. --me)

**Expected**:  
`loadConfiguration ()` fails with error message "option --mb requires an argument!"

**Actual**:  
Missing value ignored, default value applied.
```/myapp --mb
myboolean is: 1 
myenum is: 0 
myfloatcheckrange is: 1.000000 
mystringcheckdate is: 1:0 
mystringcheckvalidation is: aaa 
myunsignedshortcheckrange is: 9 
elektraGet...() was executed for all keys available in specification!
```

#### Class 2: wrong type
1. Execute ` ./myapp --mb notabool`
2. Execute ` ./myapp --mfcr notafloat`
3. Execute ` ./myapp --muscr notanunsignedshort`

**Expected**:
`loadConfiguration ()` fails with error message "type of OPTION wrong"

**Actual**:
Application crashes within `elektraGetMyboolean()` (or the other elektraGet...()s) without an error message. Exit code is -1.

#### Class 3: validation errors reported by check/* plugins
The check/* plugins seem not to be executed. Their validation is not executed.

1. Execute ` ./myapp --me illegalenumvalue`
2. Execute ` ./myapp --mfcr 99.0`
3. Execute ` ./myapp --mscd notaiso8601date`
4. Execute ` ./myapp --mscv notthestring-aaa`
5. Execute ` ./myapp --muscr 999`

**Expected**:
`loadConfiguration ()` fails with error message "Validation error for OPTION, reason: ..."

**Actual**:
Application crashes within `elektraGetMyenum()` (or the other elektraGet...()s) without an error message. Exit code is -1.

## System Information

- Elektra Version: 0.9.7
- Operating System: Ubuntu 20.04
- Versions of other relevant software: n/a

**Comment by kodebach** [comment] 2021-09-10 22:18
> can this be solved by changing the placement of gopts

`gopts` should already be called before e.g. `type`. That's why the `procgetstorage` position exists.

> Steps to Reproduce the Problem

Did you mount the spec and then `spec-mount` correctly? You didn't list this in your reproduction. Without `spec-mount` plugins like `type` wouldn't be mounted. This would explain class 2 and 3.

> Class 1: missing argument

This would be a bug in `elektraGetOpts`. It should report an error, which in turn should be reported by `gopts` and then by `kdbGet`, and finally by `elektraOpen`/`loadConfiguration`.

`gopts` should be mounted via the contract even without `spec-mount`. But if the specification itself isn't mounted, then `gopts` would be a no-op.

> Application crashes [...] without an error message. Exit code is -1.

That's the default error handler, you can set a different one with `elektraFatalErrorHandler`. But probably you won't get much more information in this case. I'm pretty sure that

**Comment by kodebach** [comment] 2021-09-11 23:50
> I think your last paragraph was accidentally cut off?

Oh sorry, it should read: "I'm pretty sure that the `type` plugin didn't run and `elektraGet*` tried to read an incompatible value". Which is exactly what happend. 

> The file myapp.overlay.spec.eqd does not actually exist on disk. Could that be the cause?

No that's mostly normal with `specload`. But you could try the option without `specload`, maybe `specload` causes some unexpected problems.

---

Honestly, I have no idea what is going on here. The errors look like `type` and the other plugins aren't executed. But the mountpoints config contains the plugins, so they should be executed. The only other explanation would be that the `spec:/` metakeys aren't copied to the non-`spec:/` keys correctly. This could be an error in the `spec` plugin, or somehow the spec data doesn't get to the `spec` plugin.

I'll look into this myself and report back, when I know more.

**Comment by qwepoizt** [comment] 2021-09-13 15:10
I looked into this and discovered - by reading the code and debugging - that:

* The `check/*` plugins (e.g. `range`, `validation`) only perform their validation during `elektraPLUGINNAMESet()` and not during `elektraPLUGINNAMEGet()`. The `...Get()` functions pass the unchanged KeySet through.

c.f. `range.c:elektraRangeGet()`:
https://github.com/ElektraInitiative/libelektra/blob/6701d9ea627a7fb6df7276c4d6fe69fa9a6b8ae4/src/plugins/range/range.c#L468-L488

* The `opts` library directly writes the parsed CLI options into the `proc:/` namespace. **It performs no `kdbSet()`**.
c.f. the documentation for `opts.c:writeOptionValues()`
https://github.com/ElektraInitiative/libelektra/blob/6701d9ea627a7fb6df7276c4d6fe69fa9a6b8ae4/src/libs/opts/opts.c#L1219-L1226

* Therefore, the `check/*` plugins' `elektraPLUGINNAMESet()` functions are not called during `elektraOpen()` and no validation is performed during startup of the application using the HL API.

@kodebach 
* Could this be the cause?
* Would a sensible fix be, to have the `check/*` plugins execute the same validation during `elektraPLUGINNAMEGet()` which is performed during `elektraPLUGINNAMESet()`?
* If not, do you have a suggestion for a fix?

**Comment by kodebach** [comment] 2021-09-13 19:53
> Could this be the cause?

Yes, I'm pretty sure this is the cause. I didn't immediately suggest it, because I thought that at least `type` also does its validation during `kdbGet`.

> Would a sensible fix be, to have the `check/*` plugins execute the same validation during `elektraPLUGINNAMEGet()` which is performed during `elektraPLUGINNAMESet()`?

I have advocated for this multiple times, because it is also a problem, if you modify the config file manually (which will be quite common for some applications). However, until now it seemed I'm the only one that was in favour of enforcing this.

> If not, do you have a suggestion for a fix?

I don't see any other option, since `proc:/` should be ignored during `kdbSet`. It doesn't make sense to store `proc:/` keys anywhere. They are per definition only relevant to the current process.

**Comment by qwepoizt** [comment] 2021-09-14 06:12
I see, thank you!

@markus2330: What do you think about adding validatuon to 
elektraPLUGINNAMEGet() ? Are there sensible alternatives?

**Comment by qwepoizt** [comment] 2021-09-15 11:26
Some `check/*` plugins already have the `postgetstorage` placement, meaning their `elektraPLUGINNAMEGet()` is executed and they could execute their validation.

If we decide to execute their validation during `elektraPLUGINNAMEGet()`, we will also have to make sure that they have the `postgetstorage` placement!

E.g. `check/validation` currently does not have `postgetstorage` thusly its `elektraPLUGINNAMEGet()` is not even executed during `elektraOpen()`.

**Comment by qwepoizt** [comment] 2021-09-15 11:35
Note: I fixed a typo in https://github.com/ElektraInitiative/libelektra/issues/4029#issue-993342197. The value of  `[mystringcheckdate]` 's `opt/arg` was `require`, now fixed to `required`.

**Comment by qwepoizt** [comment] 2021-09-15 13:41
I've split this up in 3 issues, please let's continue the discussion there:

* Class 1: missing argument (forked to
gopts: No error on missing argument  #4042)
* Class 2: wrong type (forked to
gopts: Wrong type detected too late #4043)
* Class 3: validation errors reported by check/* plugins (forked to
gopts: check/ plugins perform no validation during kdbGet() #4049)

**Comment by markus2330** [comment] 2021-09-16 15:32
> I've split this up in 3 issues, please let's continue the discussion there:

Can we close this issue then?

**Closed** 2021-09-16 15:48 UTC
