### ISSUE TITLE
homepage: build fails

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2657] opened 2019-05-01 11:02 UTC
Since https://build.libelektra.org/jenkins/job/elektra-homepage/656/console the homepage build fails with following error:

```
        Start  42: test_service_storageengine
 39/119 Test  #40: test_service_convertengine .......***Failed    7.44 sec
[==========] Running 12 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 12 tests from kdbrestServicesConvertengineTest
[ RUN      ] kdbrestServicesConvertengineTest.FindSuitablePluginCheck
[       OK ] kdbrestServicesConvertengineTest.FindSuitablePluginCheck (4223 ms)
[ RUN      ] kdbrestServicesConvertengineTest.ExportToFormatCheck
[       OK ] kdbrestServicesConvertengineTest.ExportToFormatCheck (80 ms)
[ RUN      ] kdbrestServicesConvertengineTest.ExportToFormatWithConfigCheck
[       OK ] kdbrestServicesConvertengineTest.ExportToFormatWithConfigCheck (54 ms)
[ RUN      ] kdbrestServicesConvertengineTest.ExportToFormatCheck2
/home/jenkins/workspace/elektra-homepage/src/tools/rest-backend/tests/test_service_convertengine.cpp:154: Failure
Value of: cf.isValidated ()
  Actual: true
Expected: false
[  FAILED  ] kdbrestServicesConvertengineTest.ExportToFormatCheck2 (106 ms)
```

@Namoshek do you know what this error means? How can we get a more specific validation error?

**Comment by Namoshek** [comment] 2019-05-01 14:22
To be honest, I've not the slightest idea. Might be caused by a change to the plugin under testing. I've not written any C++ ever since, so I'm having quite a hard time understanding what I did back then. 😄

**Comment by markus2330** [comment] 2019-05-01 15:14
Thank you for the quick reply nevertheless.

It seems like the round-trip validation with JSON now fails. @sanssecours do you have an idea?

**Comment by sanssecours** [comment] 2019-05-01 15:52
> @sanssecours do you have an idea?

As far as I can tell, from the code:

https://github.com/ElektraInitiative/libelektra/blob/3d3c7eb52923cf4329197a9912c9439d9b33b920/src/tools/rest-backend/model_configformat.hpp#L84-L92

and

https://github.com/ElektraInitiative/libelektra/blob/3d3c7eb52923cf4329197a9912c9439d9b33b920/src/tools/rest-backend/model_configformat.hpp#L47-L62

 YAJL **does pass** a round-trip validation after PR #2580 was merged into the `master` branch. From this **limited knowledge** I would assume replacing `ASSERT_FALSE` in

https://github.com/ElektraInitiative/libelektra/blob/3d3c7eb52923cf4329197a9912c9439d9b33b920/src/tools/rest-backend/tests/test_service_convertengine.cpp#L154

with `ASSERT_TRUE` should be the correct way to fix the problem.

**Comment by markus2330** [comment] 2019-05-01 18:14
That sounds like an easy fix! Thank you for the elaborate description!

**Closed** 2019-05-02 17:54 UTC
Labels: bug, build, good first issue, help wanted
