### ISSUE TITLE
ini plugin has problems with multiline metadata

### ISSUE THREAD

**Issue by Piankero** [ElektraInitiative/libelektra#2467] opened 2019-03-08 12:22 UTC
## Steps to Reproduce the Problem

The ini plugin does not save multiline data properly unfortunately.

Create a file with the following content
```sh
[]
mountpoint = LCDd-spec.conf
infos/plugins = ini validation

[server/driverpath]
type = string
check/type = string
check/validation = .*[\/]$
check/validation/match = LINE
check/validation/message = "The path has to contain a backslack (/) at the end"
default = "server/drivers/"
description = "Where can we find the driver modules ?
  IMPORTANT: Make sure to change this setting to reflect your
             specific setup! Otherwise LCDd won't be able to find
             the driver modules and will thus not be able to
             function properly.
  NOTE: Always place a slash as last character !"
```
Then mount it and set a valid path:
```sh
kdb mount /home/wespe/Desktop/tmp.ini spec/tmp ni                             
kdb spec-mount /tmp
kdb set /tmp/server/driverpath '/tmp/directory2/'     

#Now the error occurs because the data is saved incorrectly                                                       
kdb set /tmp/server/driverpath '/tmp/directory/' 
#> Using name user/tmp/server/driverpath
#> The command kdb set failed while accessing the key database with the info:
#>  Sorry, 1 warning was issued ;(
#>  Warning (#52):
#> 	Description: could not type check value of key
#> 	Ingroup: plugin
#> 	Module: type
#> 	At: /media/wespe/extended/repository/libelektra/src/plugins/type/type.cpp:31
#> 	Reason: The type string failed to match for user/tmp/server/IMPORTANT: Make sure to change this setting to reflect your with string: 
#> 	Mountpoint: user/tmp
#> 	Configfile: /home/wespe/.config/kdb/user/LCDd-spec.conf.3875:1552046962.490367.tmp
#> Sorry, the error (#42) occurred ;(
#> Description: key value failed to validate
#> Reason: The path has to contain a backslack (/) at the end
#> Ingroup: plugin
#> Module: validator
#> At: /media/wespe/extended/repository/libelektra/src/plugins/validation/validation.c:148
#> Mountpoint: user/tmp
#> Configfile: /home/wespe/.config/kdb/user/LCDd-spec.conf.3875:1552046962.490367.tmp
```
Despite a correct path, the file which contains the data has multiple lines and the ini plugins seems to also take these into account.

When I look into the file where it is saved I see the following content:
```
[server]
#@META check/type = string
#@META check/validation = .*[\/]$
#@META check/validation/match = LINE
#@META check/validation/message = The path has to contain a backslack (/) at the end
#@META default = server/drivers/
#@META description = Where can we find the driver modules ?
  IMPORTANT: Make sure to change this setting to reflect your
             specific setup! Otherwise LCDd won't be able to find
             the driver modules and will thus not be able to
             function properly.
  NOTE: Always place a slash as last character !
#@META type = string
driverpath = /tmp/directory2/
```

## Expected Result

Multiline metadata are allowed

## Actual Result

Multiline metadata cause problems

## System Information

- Elektra Version: 0.8.26

**Comment by markus2330** [comment] 2019-03-09 19:05
Thank you for reporting this bug!

The bug can also be reproduced if the default plugin is not ini.

I see here two problems:

1. the metadata from spec should not be copied into the config file (spec plugin seems to not remove the metadata, I think this is caused by wrong/missing positioning and will hopefully be fixed by @mpranj)
2. ini plugin does not support multi-line metadata. This should be no problem once 1. is fixed

**Comment by Piankero** [comment] 2019-03-09 20:14
Using the `dump` plugin though mitigates this problem

**Comment by markus2330** [comment] 2019-03-09 21:52
The dump plugin in infos/plugins of course does. But the dump plugin as default plugin?

Btw. 0.6.28 would be a very old Elektra version but it did not exist.

**Comment by Piankero** [comment] 2019-03-09 21:54
> But the dump plugin as default plugin?

What exactly is the question here? If the dump plugin is a senseful default plugin?

> Btw. 0.6.28 would be a very old Elektra version but it did not exist.

That was actually  my mistake, it is 0.8.26 of course.

**Comment by markus2330** [comment] 2019-03-09 22:15
>  What exactly is the question here? If the dump plugin is a senseful default plugin?

The question is if your statement "Default plugin is ini" in the bug report is relevant to this bug.

**Comment by Piankero** [comment] 2019-03-10 07:50
I thought it would because the file is saved in the `ini` format. But this actually comes from this line: `infos/plugins = ini validation`. I removed that sentence stating me default plugin

**Comment by alexsaber** [comment] 2019-03-20 19:46
Hi! Can you please assign me to this issue? I have picked 3 more ini related problems.

**Comment by markus2330** [comment] 2020-04-12 08:39
Closed as we favor TOML plugin now.

**Closed by markus2330** 2020-04-12 08:39 UTC
