### ISSUE TITLE
context: failing test cases

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#964] opened 2016-09-16 20:49 UTC
```
       Start  18: test_getenv
 18/150 Test  #18: test_getenv ........................***Failed    0.27 sec
[==========] Running 13 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 13 tests from GetEnv
[ RUN      ] GetEnv.NonExist
[       OK ] GetEnv.NonExist (0 ms)
[ RUN      ] GetEnv.ExistOverride
/home/markus/Projekte/Elektra/current/src/libs/getenv/tests/test_getenv.cpp:23: Failure
Expected: (getenv ("does-exist")) != (static_cast<char *> (nullptr)), actual: NULL vs NULL
[  FAILED  ] GetEnv.ExistOverride (19 ms)
[ RUN      ] GetEnv.ExistOverrideFallback
[       OK ] GetEnv.ExistOverrideFallback (19 ms)
[ RUN      ] GetEnv.ExistEnv
[       OK ] GetEnv.ExistEnv (20 ms)
[ RUN      ] GetEnv.ExistEnvFallback
[       OK ] GetEnv.ExistEnvFallback (19 ms)
[ RUN      ] GetEnv.ExistFallback
[       OK ] GetEnv.ExistFallback (18 ms)
[ RUN      ] GetEnv.ExistFallbackFallback
[       OK ] GetEnv.ExistFallbackFallback (19 ms)
[ RUN      ] GetEnv.OpenClose
[       OK ] GetEnv.OpenClose (20 ms)
[ RUN      ] GetEnv.OpenCloseFallback
[       OK ] GetEnv.OpenCloseFallback (22 ms)
[ RUN      ] GetEnv.ArgvParam
/home/markus/Projekte/Elektra/current/src/libs/getenv/tests/test_getenv.cpp:132: Failure
Expected: (k) != (static_cast<ckdb::Key *> (nullptr)), actual: NULL vs NULL
[  FAILED  ] GetEnv.ArgvParam (22 ms)
[ RUN      ] GetEnv.ArgvParamUninvolved
/home/markus/Projekte/Elektra/current/src/libs/getenv/tests/test_getenv.cpp:160: Failure
Expected: (k) != (static_cast<ckdb::Key *> (nullptr)), actual: NULL vs NULL
[  FAILED  ] GetEnv.ArgvParamUninvolved (22 ms)
[ RUN      ] GetEnv.NameArgv0
/home/markus/Projekte/Elektra/current/src/libs/getenv/tests/test_getenv.cpp:177: Failure
Expected: (k) != (static_cast<ckdb::Key *> (nullptr)), actual: NULL vs NULL
[  FAILED  ] GetEnv.NameArgv0 (22 ms)
[ RUN      ] GetEnv.NameExplicit
/home/markus/Projekte/Elektra/current/src/libs/getenv/tests/test_getenv.cpp:196: Failure
Expected: (k) != (static_cast<ckdb::Key *> (nullptr)), actual: NULL vs NULL
[  FAILED  ] GetEnv.NameExplicit (22 ms)
[----------] 13 tests from GetEnv (245 ms total)

[----------] Global test environment tear-down
[==========] 13 tests from 1 test case ran. (245 ms total)
[  PASSED  ] 8 tests.
[  FAILED  ] 5 tests, listed below:
[  FAILED  ] GetEnv.ExistOverride
[  FAILED  ] GetEnv.ArgvParam
[  FAILED  ] GetEnv.ArgvParamUninvolved
[  FAILED  ] GetEnv.NameArgv0
[  FAILED  ] GetEnv.NameExplicit

 5 FAILED TESTS

        Start  19: test_fork
 19/150 Test  #19: test_fork ..........................   Passed    0.04 sec
        Start  20: test_context
 20/150 Test  #20: test_context .......................***Failed    0.26 sec
[==========] Running 12 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 12 tests from Context
[ RUN      ] Context.Exist
[       OK ] Context.Exist (20 ms)
[ RUN      ] Context.ExistWithContext
[       OK ] Context.ExistWithContext (19 ms)
[ RUN      ] Context.ExistWithContextCascading
[       OK ] Context.ExistWithContextCascading (20 ms)
[ RUN      ] Context.ExistWithContextOverrideCascading
/home/markus/Projekte/Elektra/current/src/libs/getenv/tests/test_context.cpp:72: Failure
Value of: f
  Actual: 0x21a4cb0
Expected: k
Which is: 0x21a0240
[  FAILED  ] Context.ExistWithContextOverrideCascading (20 ms)
[ RUN      ] Context.ExistWithContextOverrideCascadingSystem
/home/markus/Projekte/Elektra/current/src/libs/getenv/tests/test_context.cpp:90: Failure
Value of: f
  Actual: 0x21b5730
Expected: k
Which is: 0x21b5890
[  FAILED  ] Context.ExistWithContextOverrideCascadingSystem (19 ms)
[ RUN      ] Context.ExistWithContextOverrideCascadingDir
/home/markus/Projekte/Elektra/current/src/libs/getenv/tests/test_context.cpp:109: Failure
Value of: f
  Actual: 0x21580e0
Expected: k
Which is: 0x2157ce0
[  FAILED  ] Context.ExistWithContextOverrideCascadingDir (20 ms)
[ RUN      ] Context.ExistWithContextOverrideCascadingProc
/home/markus/Projekte/Elektra/current/src/libs/getenv/tests/test_context.cpp:127: Failure
Value of: f
  Actual: 0x214ac40
Expected: k
Which is: 0x2146100
[  FAILED  ] Context.ExistWithContextOverrideCascadingProc (19 ms)
[ RUN      ] Context.ExistWithContextOverrideCascadingWithSlash
/home/markus/Projekte/Elektra/current/src/libs/getenv/tests/test_context.cpp:144: Failure
Value of: f
  Actual: 0x213c1b0
Expected: k
Which is: 0x213e570
[  FAILED  ] Context.ExistWithContextOverrideCascadingWithSlash (20 ms)
[ RUN      ] Context.NameExplicit
[       OK ] Context.NameExplicit (20 ms)
[ RUN      ] Context.ExistWithContextOverrideCascadingOverrideUser
/home/markus/Projekte/Elektra/current/src/libs/getenv/tests/test_context.cpp:178: Failure
Value of: f
  Actual: NULL
Expected: k
Which is: 0x214c700
[  FAILED  ] Context.ExistWithContextOverrideCascadingOverrideUser (20 ms)
[ RUN      ] Context.ExistWithContextOverrideCascadingOverrideSystem
/home/markus/Projekte/Elektra/current/src/libs/getenv/tests/test_context.cpp:197: Failure
Value of: f
  Actual: NULL
Expected: k
Which is: 0x213fb60
[  FAILED  ] Context.ExistWithContextOverrideCascadingOverrideSystem (20 ms)
[ RUN      ] Context.ExistWithContextOverrideCascadingOverride
/home/markus/Projekte/Elektra/current/src/libs/getenv/tests/test_context.cpp:215: Failure
Value of: f
  Actual: NULL
Expected: k
Which is: 0x21aee90
[  FAILED  ] Context.ExistWithContextOverrideCascadingOverride (20 ms)
[----------] 12 tests from Context (237 ms total)

[----------] Global test environment tear-down
[==========] 12 tests from 1 test case ran. (237 ms total)
[  PASSED  ] 4 tests.
[  FAILED  ] 8 tests, listed below:
[  FAILED  ] Context.ExistWithContextOverrideCascading
[  FAILED  ] Context.ExistWithContextOverrideCascadingSystem
[  FAILED  ] Context.ExistWithContextOverrideCascadingDir
[  FAILED  ] Context.ExistWithContextOverrideCascadingProc
[  FAILED  ] Context.ExistWithContextOverrideCascadingWithSlash
[  FAILED  ] Context.ExistWithContextOverrideCascadingOverrideUser
[  FAILED  ] Context.ExistWithContextOverrideCascadingOverrideSystem
[  FAILED  ] Context.ExistWithContextOverrideCascadingOverride

 8 FAILED TESTS

```

**Comment by markus2330** [comment] 2016-09-16 20:50
@tom-wa to reproduce you need elektra-intercept-getenv in /etc/ld.so.preload

**Comment by tom-wa** [comment] 2016-09-16 21:28
seems like test_getenv already failed before #902 
dunno if it's easy to fix/find

**Comment by markus2330** [comment] 2016-09-16 21:34
Can you reproduce it? For me it does not happen on every computer.

**Comment by tom-wa** [comment] 2016-09-16 21:36
first thing i did was to check if it worked before #902. test_getenv failed, test_context didn't.
but i can't reproduce it with the latest version. not sure what's going on here

**Comment by tom-wa** [comment] 2016-09-16 21:39
i did remove ld.so.cache and rebuild it completely before testing with the latest version, not sure if it might be related

**Comment by markus2330** [comment] 2016-09-16 22:22
And you do not get the error anymore?

**Comment by tom-wa** [comment] 2016-09-16 22:33
yeah, rebuilt and ran it several times, no issues.

**Comment by markus2330** [comment] 2016-09-16 22:34
Thanks for testing!

**Comment by markus2330** [comment] 2016-09-20 13:32
@tom-wa Are you sure you still had getenv in `/etc/ld.so.preload` after rebuilding and recreating the `ld.so.cache`?

On one machine I consistently get the errors:

```
 18/149 Test  #18: test_getenv ........................***Failed    0.28 sec
[==========] Running 13 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 13 tests from GetEnv
[ RUN      ] GetEnv.NonExist
[       OK ] GetEnv.NonExist (0 ms)
[ RUN      ] GetEnv.ExistOverride
/home/markus/Projekte/Elektra/current/src/libs/getenv/tests/test_getenv.cpp:23: Failure
Expected: (getenv ("does-exist")) != (static_cast<char *> (nullptr)), actual: NULL vs NULL
[  FAILED  ] GetEnv.ExistOverride (22 ms)
[ RUN      ] GetEnv.ExistOverrideFallback
[       OK ] GetEnv.ExistOverrideFallback (21 ms)
[ RUN      ] GetEnv.ExistEnv
[       OK ] GetEnv.ExistEnv (20 ms)
[ RUN      ] GetEnv.ExistEnvFallback
[       OK ] GetEnv.ExistEnvFallback (21 ms)
[ RUN      ] GetEnv.ExistFallback
[       OK ] GetEnv.ExistFallback (20 ms)
[ RUN      ] GetEnv.ExistFallbackFallback
[       OK ] GetEnv.ExistFallbackFallback (23 ms)
[ RUN      ] GetEnv.OpenClose
[       OK ] GetEnv.OpenClose (20 ms)
[ RUN      ] GetEnv.OpenCloseFallback
[       OK ] GetEnv.OpenCloseFallback (21 ms)
[ RUN      ] GetEnv.ArgvParam
/home/markus/Projekte/Elektra/current/src/libs/getenv/tests/test_getenv.cpp:132: Failure
Expected: (k) != (static_cast<ckdb::Key *> (nullptr)), actual: NULL vs NULL
[  FAILED  ] GetEnv.ArgvParam (19 ms)
[ RUN      ] GetEnv.ArgvParamUninvolved
/home/markus/Projekte/Elektra/current/src/libs/getenv/tests/test_getenv.cpp:160: Failure
Expected: (k) != (static_cast<ckdb::Key *> (nullptr)), actual: NULL vs NULL
[  FAILED  ] GetEnv.ArgvParamUninvolved (21 ms)
[ RUN      ] GetEnv.NameArgv0
/home/markus/Projekte/Elektra/current/src/libs/getenv/tests/test_getenv.cpp:177: Failure
Expected: (k) != (static_cast<ckdb::Key *> (nullptr)), actual: NULL vs NULL
[  FAILED  ] GetEnv.NameArgv0 (20 ms)
[ RUN      ] GetEnv.NameExplicit
/home/markus/Projekte/Elektra/current/src/libs/getenv/tests/test_getenv.cpp:196: Failure
Expected: (k) != (static_cast<ckdb::Key *> (nullptr)), actual: NULL vs NULL
[  FAILED  ] GetEnv.NameExplicit (20 ms)
[----------] 13 tests from GetEnv (248 ms total)

[----------] Global test environment tear-down
[==========] 13 tests from 1 test case ran. (248 ms total)
[  PASSED  ] 8 tests.
[  FAILED  ] 5 tests, listed below:
[  FAILED  ] GetEnv.ExistOverride
[  FAILED  ] GetEnv.ArgvParam
[  FAILED  ] GetEnv.ArgvParamUninvolved
[  FAILED  ] GetEnv.NameArgv0
[  FAILED  ] GetEnv.NameExplicit

 5 FAILED TESTS

        Start  19: test_fork
 19/149 Test  #19: test_fork ..........................   Passed    0.06 sec
        Start  20: test_context
 20/149 Test  #20: test_context .......................***Failed    0.27 sec
[==========] Running 12 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 12 tests from Context
[ RUN      ] Context.Exist
[       OK ] Context.Exist (20 ms)
[ RUN      ] Context.ExistWithContext
[       OK ] Context.ExistWithContext (20 ms)
[ RUN      ] Context.ExistWithContextCascading
[       OK ] Context.ExistWithContextCascading (20 ms)
[ RUN      ] Context.ExistWithContextOverrideCascading
/home/markus/Projekte/Elektra/current/src/libs/getenv/tests/test_context.cpp:72: Failure
Value of: f
  Actual: 0x1983340
Expected: k
Which is: 0x1983220
[  FAILED  ] Context.ExistWithContextOverrideCascading (20 ms)
[ RUN      ] Context.ExistWithContextOverrideCascadingSystem
/home/markus/Projekte/Elektra/current/src/libs/getenv/tests/test_context.cpp:90: Failure
Value of: f
  Actual: 0x19808c0
Expected: k
Which is: 0x19807a0
[  FAILED  ] Context.ExistWithContextOverrideCascadingSystem (19 ms)
[ RUN      ] Context.ExistWithContextOverrideCascadingDir
/home/markus/Projekte/Elektra/current/src/libs/getenv/tests/test_context.cpp:109: Failure
Value of: f
  Actual: 0x19331f0
Expected: k
Which is: 0x19330d0
[  FAILED  ] Context.ExistWithContextOverrideCascadingDir (20 ms)
[ RUN      ] Context.ExistWithContextOverrideCascadingProc
/home/markus/Projekte/Elektra/current/src/libs/getenv/tests/test_context.cpp:127: Failure
Value of: f
  Actual: 0x19b6ac0
Expected: k
Which is: 0x19b69a0
[  FAILED  ] Context.ExistWithContextOverrideCascadingProc (20 ms)
[ RUN      ] Context.ExistWithContextOverrideCascadingWithSlash
/home/markus/Projekte/Elektra/current/src/libs/getenv/tests/test_context.cpp:144: Failure
Value of: f
  Actual: 0x197c070
Expected: k
Which is: 0x197bf50
[  FAILED  ] Context.ExistWithContextOverrideCascadingWithSlash (19 ms)
[ RUN      ] Context.NameExplicit
[       OK ] Context.NameExplicit (20 ms)
[ RUN      ] Context.ExistWithContextOverrideCascadingOverrideUser
/home/markus/Projekte/Elektra/current/src/libs/getenv/tests/test_context.cpp:178: Failure
Value of: f
  Actual: NULL
Expected: k
Which is: 0x196a3b0
[  FAILED  ] Context.ExistWithContextOverrideCascadingOverrideUser (20 ms)
[ RUN      ] Context.ExistWithContextOverrideCascadingOverrideSystem
/home/markus/Projekte/Elektra/current/src/libs/getenv/tests/test_context.cpp:197: Failure
Value of: f
  Actual: NULL
Expected: k
Which is: 0x19a64d0
[  FAILED  ] Context.ExistWithContextOverrideCascadingOverrideSystem (19 ms)
[ RUN      ] Context.ExistWithContextOverrideCascadingOverride
/home/markus/Projekte/Elektra/current/src/libs/getenv/tests/test_context.cpp:215: Failure
Value of: f
  Actual: NULL
Expected: k
Which is: 0x196a090
[  FAILED  ] Context.ExistWithContextOverrideCascadingOverride (20 ms)
[----------] 12 tests from Context (237 ms total)

[----------] Global test environment tear-down
[==========] 12 tests from 1 test case ran. (237 ms total)
[  PASSED  ] 4 tests.
[  FAILED  ] 8 tests, listed below:
[  FAILED  ] Context.ExistWithContextOverrideCascading
[  FAILED  ] Context.ExistWithContextOverrideCascadingSystem
[  FAILED  ] Context.ExistWithContextOverrideCascadingDir
[  FAILED  ] Context.ExistWithContextOverrideCascadingProc
[  FAILED  ] Context.ExistWithContextOverrideCascadingWithSlash
[  FAILED  ] Context.ExistWithContextOverrideCascadingOverrideUser
[  FAILED  ] Context.ExistWithContextOverrideCascadingOverrideSystem
[  FAILED  ] Context.ExistWithContextOverrideCascadingOverride

 8 FAILED TESTS
```

Btw. I also think its rather unrelated to #902. Can you write the `kdb stash` #876 for easier debugging?

**Comment by tom-wa** [comment] 2016-09-20 14:34
>Btw. I also think its rather unrelated to #902 

i'm sure it is because i reverted everything to before #902 was merged to test it and it failed, but i really can't reproduce it now after clearing ld.so.cache 

>Are you sure you still had getenv in /etc/ld.so.preload after rebuilding and recreating the ld.so.cache?

yeah, because i had some (unrelated) building issues i thought could stem from some intercepted environment variable.

**Comment by tom-wa** [comment] 2016-09-20 14:36
what also confuses me is that the testcases work fine when the library is not preloaded

**Closed** 2016-10-12 21:14 UTC
