### ISSUE TITLE
CMake: Compilation starts before kdberrors.h is written

### ISSUE THREAD

**Issue by sl1pkn07** [ElektraInitiative/libelektra#258] opened 2015-08-22 14:07 UTC
with latest commit

    In file included from /home/sl1pkn07/aplicaciones/elektra-git/src/elektra/src/plugins/type/type.cpp:17:0:
    /home/sl1pkn07/aplicaciones/elektra-git/src/elektra/src/bindings/cpp/include/kdbplugin.hpp: In function 'ckdb::KeySet* elektraErrorSpecification()':
    /home/sl1pkn07/aplicaciones/elektra-git/src/elektra/src/bindings/cpp/include/kdbplugin.hpp:27:1: error: a template declaration cannot appear at block scope
     template <typename Delegated>
     ^
    /home/sl1pkn07/aplicaciones/elektra-git/src/elektra/src/plugins/type/type.cpp:19:9: error: 'Delegator' does not name a type
     typedef Delegator<elektra::TypeChecker> TC;
         ^
    /home/sl1pkn07/aplicaciones/elektra-git/src/elektra/src/plugins/type/type.cpp:21:8: error: expected unqualified-id before string constant
     extern "C"
        ^
    /home/sl1pkn07/aplicaciones/elektra-git/src/elektra/src/plugins/type/type.cpp:95:1: error: expected '}' at end of input
     }
     ^

build with

    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DBUILD_TESTING=OFF \
    -DBUILD_FULL=OFF \
    -DBUILD_STATIC=OFF \
    -DENABLE_TESTING=OFF \
    -DENABLE_CXX11=ON \
    -DPLUGINS=ALL

**Comment by markus2330** [comment] 2015-08-23 08:36
Thank you for reporting the bug!

Which compiler are you using? It seems like KDBERRORS_H was not set, but I am puzzled why this is the case.

133afae686a270a766bb5400c9e4865913309ac9 might provide the fix, please confirm.

**Comment by sl1pkn07** [comment] 2015-08-23 11:20
nope, same error in same point

my compiler is GCC 5.2.0 (archlinux)

**Comment by manuelm** [comment] 2015-08-23 12:06
@markus2330 I've just upgrade a bunch of packages on debian-unstable-mm, including gcc to 5.2.1

But I'm unable to reproduce this

**Comment by sl1pkn07** [comment] 2015-08-23 13:33
ok. i dont't know why but now can build (maybe a git mistake)

but when install the project say

    CMake Error at scripts/cmake_install.cmake:64 (file):
      file INSTALL cannot find
      "/home/sl1pkn07/aplicaciones/elektra-git/src/elektra/scripts/configure-debian-wheezy-local".
    Call Stack (most recent call first):
      cmake_install.cmake:38 (include)


maybe https://github.com/ElektraInitiative/libelektra/commit/e60e63ab2d3ccc0a98de5651aba5b32d3d5a948b is the culprit (remove the file but not remove the rule in the CMakeLists.txt)

greetings

**Comment by sl1pkn07** [comment] 2015-08-23 15:01
I make more test, the problem avobe is when rebuild the project without remove the sources first (all code)

but i'm not sure why, because use a other folder to build, and clean it before start the build

    rm -fr build
    mkdir -p build
    cd build
    cmake ../elektra \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DBUILD_TESTING=OFF \
      -DBUILD_FULL=OFF \
      -DBUILD_STATIC=OFF \
      -DENABLE_TESTING=OFF \
      -DENABLE_CXX11=ON \
      -DPLUGINS=ALL
    make

**Comment by markus2330** [comment] 2015-08-23 19:26
Thanks for reporting the problem with configure-debian-wheezy-local in 64dba6cb26d4c381406d93074dbe6dd1406559e6

I doubt, however, that it has anything to do with your problem. Could you please preprocess the file:

    cd src/plugins/type
    make type.i
    editor CMakeFiles/elektra-type.dir/type.cpp.i

Maybe you find a weird combination of set macros.

**Comment by sl1pkn07** [comment] 2015-08-23 19:43
└───╼  make type.i
    Preprocessing CXX source to CMakeFiles/elektra-type.dir/type.cpp.i
    Preprocessing CXX source to CMakeFiles/elektra-type-objects.dir/type.cpp.i

https://www.dropbox.com/s/e3g0rysdn821qmy/type.cpp.i?dl=0

**Comment by markus2330** [comment] 2015-08-26 17:23
The problem might be somewhere in the kdberrors.h (thats included directly above the problematic lines)

But I do not see any significant difference in our preprocessed files (only __builtin_va_start differs completely).

Can you give me the compilation error when the type plugin is disabled?

    cmake -DPLUGINS="ALL;-type" /path/to/libelektra

**Comment by sl1pkn07** [comment] 2015-08-28 04:26
tested , but have a weird result

if build with all my threads (24) failbuild with random error (same error described in this issue, and new  other errors).

then test with only 8 threads, but still fail. 

but if test with 7 or less threads, then build OK without any error. inclusive if rebuild the project again. 

tested with and without you build rule posted above

**Comment by markus2330** [comment] 2015-08-28 19:58
It actually is weird. First I thought maybe kdberrors.h is not fully written when the compilation process starts. (This rarely happend, even though kdberrors.h is added as dependency.) But then a second try of `make` should fix the problem.

Which build system are you using (cmake build system generator, e.g. Makefiles)?

When you say threads, do you mean processes (-j option of make)?

Could you please also try with

    cmake -DPLUGINS="ALL;-type" /path/to/libelektra

it would help to limit what the error actually is.

**Comment by sl1pkn07** [comment] 2015-08-28 20:50
use PKGBUILD script ('makepkg' is the build system in Archlinux)

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=elektra-git (I'll update the pkgbuild, when this issue is fixed)

the "-jcores" is passed to build system with makepkg internal variable (MAKEFLAGS="-j24") (set in /etc/makepkg.conf)

the complete build log with '-DPLUGINS="ALL;-type"'

http://sl1pkn07.wtf/paste/view/2d2ea307

mmm I think I forget to post a prior error to error posted in the first post

**Comment by markus2330** [comment] 2015-08-30 14:06
The first error is:

````
/home/sl1pkn07/aplicaciones/elektra-git/src/build/src/include/kdberrors.h: In function 'elektraAddWarningf36':
/home/sl1pkn07/aplicaciones/elektra-git/src/build/src/include/kdberrors.h:3:0: error: unterminated #ifndef
````

So its clear that the compilation starts before the file kdberrors.h was fully written.
A possible solution would be to move the generation of kdberrors.h to CMake stage. That also has the advantage that cross-compilation gets easier. As a downside it means that src/liberror/exporterrors.cpp needs to be rewritten in CMake.

**Comment by markus2330** [comment] 2015-09-06 09:03
@sl1pkn07 Is it possible that it is a filesystem issue? Can you try to reproduce it in on tmpfs?

Even when using -j50 on a up-to-date machine I do not get these compilation error.

Another possible cmake solution would be to create a top-level target in src/include (using add_custom_target) that generates kdberrors.h (liberror needs to be built before) and have all other targets depend on it (that would be the hard part).

But if its a filesystem issue, it won't be useful.

**Comment by sl1pkn07** [comment] 2015-09-08 15:28
tested on tmpfs. Zero issues

**Comment by markus2330** [comment] 2015-09-08 16:31
Can we close the issue then? Because I am afraid additional sync(2) will also not solve the problem, but only changes in the local setup (mountoptions or similar).

**Comment by sl1pkn07** [comment] 2015-09-08 16:45
i think yes. can be close the issue

**Closed** 2015-09-08 19:04 UTC

**Comment by sl1pkn07** [comment] 2016-01-03 23:56
nope, need reopen this issue

i found the problem

if build with '-DBUILD_TESTING=ON' all build ok. but if set '-DBUILD_TESTING=OFF', the error of this issue is back. also if not add : '-DPLUGINS="ALL;-type"', the fail in cmake configure process: 

    CMake Error at cmake/Modules/LibAddTest.cmake:54 (set_property):
      set_property given TEST names that do not exist:
        testmod_type
    Call Stack (most recent call first):
      src/plugins/type/CMakeLists.txt:13 (add_gtest)


if set -DBUILD_FULL=OFF, all build. but if set -DBUILD_FULL=ON, or no set in cmake (i mean, no put in the cmake command) also fails in same point

this is not problem of build on tmpfs(like now) or in phisical disk

greetings

**Comment by markus2330** [comment] 2016-01-04 06:14
I am a bit confused: The error message seems to be unrelated to "not written kdberrors" and the bug is not reopend? However, the message you posted is clear and should be fixed in 508daab.

Thanks for reporting! Please (re)open if you find any more issues.

**Comment by sl1pkn07** [comment] 2016-01-04 08:50
Simply, 
that message (testmode_type) only appears when set '-DBUILD_TESTING=OFF' and '-DPLUGINS=ALL'. can jump the error if set '-DPLUGINS=ALL;-type'. 

But then back the error related with kerberos.

Only fix if set -DBUILD_TESTING=ON and -DBUILD- FULL=OFF, other combinación get the sale fail (kerberos).

**Comment by markus2330** [comment] 2016-01-04 11:14
testmode_type should be fixed, you should not need the `-DPLUGINS=ALL;-type` workaround, please report if it is still not fixed for you.

I am still a bit confused, what has kerberos to do with it? (Do you mean kdberrors.h? Please post exact error messages.) Also "combinación get the sale fail" makes me puzzled. (Please give exact cmake commandline you would like to have + error you get with latest Elektra version build on tmpfs)

I now fixed `-DBUILD_TESTING=OFF` (had some more problems) and the commandline as given in #432 compiles now too (3 unit tests still have problems without BUILD_FULL nor BUILD_STATIC though, to be fixed soon).

**Comment by sl1pkn07** [comment] 2016-01-04 11:21
the error with kerberos is described here https://github.com/ElektraInitiative/libelektra/issues/258#issuecomment-135884867

let me time to test the latest changes

**Comment by sl1pkn07** [comment] 2016-01-04 11:44
- build with '-DBUILD_TESTING=OFF' is fixed. and no need more set '-DPLUGINS=ALL;-type'.

- build with '-DBUILD_FULL=ON' fails if use 'make -j24' (all my cores). log : http://sl1pkn07.wtf/paste/view/e4c210e4
but if use -j1 build OK

all over tmpfs (ram)

tested with commit 8551d35 and this cmake options

      cmake ../elektra \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DENABLE_TESTING=ON \
        -DBUILD_TESTING=OFF \
        -DBUILD_SHARED=ON \
        -DBUILD_STATIC=OFF \
        -DBUILD_FULL=ON \
        -DTOOLS=ALL \
        -DPLUGINS=ALL \
        -DBINDINGS=ALL \
        -DLUA_INCLUDE_DIR=/usr/include/lua5.2

**Comment by markus2330** [comment] 2016-01-04 12:05
I cannot reproduce it, even with -j24 (I do not have so many cores though). 

9e351ff4075bdb9552d58da04f11451942fe87ba might help, can you try? Does it fail with every number above -j1? Another workaround would be to use `make -j 24 || make -j 24`, once the file include/kdberrors.h is fully stored on disc, there should be no problem anymore.

**Comment by sl1pkn07** [comment] 2016-01-04 13:11
9e351ff no helps (with -j24)

yes, 'make || make' can avoid the error, but i think is a little workground that needs fixing

>Does it fail with every number above -j1?

tested with:

    for _jobs in $(seq 1 24); do echo "=====>BUILD WITH ${_job} THREADS<=====" && LC_ALL=C makepkg MAKEFLAGS=-j${_jobs}; done

fail with 15, 19, 20, 21, 23 and 24 jobs


btw, all of this is for I maintain the AUR package elektra-git https://aur.archlinux.org/packages/elektra-git/ (sources from git instead of for "zip") (only maintain, i'm not coder :( (only little fixes))

the updated PKGBUILD is this http://sl1pkn07.wtf/paste/view/325631b6 (uploaded when all has fixed).

greetings

**Comment by markus2330** [comment] 2016-01-04 17:23
Hello, one more try: In 9722cd914f58b36fd03920b6b66edecaa944ea5e should render the error impossible, either kdberrors.h is found and has correct content or is not there at all. (Unfortunately this is impossible with C99, it needs POSIX, thus it was not there in the first place. But we will find a solution for this, if it really helps in your -j24 situation.)

Yes, I know that you maintain the AUR package and we are very thankful for it! Some of the elektra-devs use Arch. Answers about the dependencies are in #433.

**Comment by markus2330** [comment] 2016-01-04 22:24
Please tell me if you can still reproduce this issue and the number of jobs needed to fail it.

Thank you!

**Comment by sl1pkn07** [comment] 2016-01-04 22:44
in test. give me time! XD

**Comment by markus2330** [comment] 2016-01-04 22:59
Thx!

**Comment by manuelm** [comment] 2016-01-04 23:05
Instead of workarounds, we should rather fix the multiple/parallel generations of `kdberrors.h`. From cmake `add_custom_command`: ```Do not list the output in more than one independent target that may build in parallel or the two instances of the rule may conflict (instead use add_custom_target to drive the command and make the other targets depend on that one).```

**Comment by manuelm** [comment] 2016-01-04 23:09
What about `add_custom_target` + `ALL`-flag?

**Comment by markus2330** [comment] 2016-01-04 23:12
I gladly accept PRs. Its difficult to fix it without any way to reproduce the issue and its easy to introduce new issues. I do not know if ALL targets are guaranteed to be build before anything else.

**Comment by manuelm** [comment] 2016-01-04 23:23
Try running a parallel build with high concurrency and look out for multiple `Generating ../../include/kdberrors.h`. The build doesn't have to fail.

**Comment by markus2330** [comment] 2016-01-04 23:30
Yes, one can do that. Still, one should read the CMake docs, so that the behaviour won't change in the next version. I agree it should be done right.

**Comment by sl1pkn07** [comment] 2016-01-04 23:50
tested 25 times with -j24. all done :D

**Comment by markus2330** [comment] 2016-01-04 23:50
Thank you! @manuelm thank you for your effort too, the hints will be valueable when we trap into the issue again.

**Comment by markus2330** [comment] 2016-01-05 00:16
@sl1pkn07 all unittest should now also run with BUILD_SHARED only.

In the next release we might even prefer to run unittest as BUILD_SHARED, even if BUILD_FULL is available (as suggested by @manuelm). It tests "more" (the module loading/unloading), but is also a (lot) slower for the memtests.

Mingw build should work now too (It was broken because of adding the fsync/rename in exporterrors).

Thanks again!
